'use client';

import {FormEvent,useEffect,useMemo,useState} from 'react';
import {spareParts} from '../product-data';

type Product={id:number;slug:string;name:string;sku:string;category:string;compatibility:string;price:number;currency:'TRY';stock:number;image:number;imageUrl?:string;active:boolean;description:string;brand:string;condition:'new';gtin?:string;mpn?:string};
type CartLine={id:number;qty:number};
type OrderLine={id:number;name:string;sku:string;qty:number;unitPrice:number};
type Order={id:string;customer:string;contact:string;address:string;total:number;status:string;createdAt:string;lines?:OrderLine[]};
type AdminMachine={slug:string;name:string;kind:string;fit:string;area:string;image?:string;description?:string};
type MachineAdminState={hidden:string[];custom:AdminMachine[]};
const machineAdminKey='zy-machine-admin';
const baseMachines:AdminMachine[]=[
 {slug:'ecoline-b250-binicili-zemin-temizleme-otomati',name:'Berker Ecoline B250',kind:'Binicili',fit:'Geniş alanlarda yüksek kapasiteli temizlik',area:'AVM, fabrika, depo ve otopark',image:'/b250-showcase.webp'},
 {slug:'ecoline-b140-binicili-zemin-temizleme-makinasi',name:'Berker Ecoline B140',kind:'Binicili',fit:'Dar ve kalabalık alanlarda çevik temizlik',area:'Okul, hastane, market ve otel',image:'/b140-showcase.webp'},
 {slug:'ecoline-b60-zemin-temizleme-makinasi',name:'Berker Ecoline B60',kind:'İtmeli',fit:'Günlük profesyonel temizlik için kompakt çözüm',area:'AVM, fabrika, hastane ve depo',image:'/b60-showcase.webp'},
 {slug:'berker-ecoline-c70-binicili-zemin-yikama-makinasi',name:'Berker Ecoline C70',kind:'Binicili',fit:'Çift fırçalı yüksek verimli çözüm',area:'Süpermarket, fabrika ve depo',image:'/c70-showcase.webp'},
 {slug:'berker-ecoline-b45-akulu-itmeli-zemin-otomati',name:'Berker Ecoline B45',kind:'İtmeli',fit:'Orta ölçekli alanlar için pratik temizlik',area:'Fabrika, depo, okul ve ofis',image:'/b45-showcase.webp'},
];

const defaults:Product[]=spareParts.map(({image:imageUrl,imageIndex,metaDescription:_,...product})=>({...product,image:imageIndex,imageUrl}));

const money=(n:number)=>new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY'}).format(n);
const load=<T,>(key:string,fallback:T):T=>{if(typeof window==='undefined')return fallback;try{return JSON.parse(localStorage.getItem(key)||'null')||fallback}catch{return fallback}};
const save=(key:string,value:unknown)=>{if(typeof window!=='undefined')localStorage.setItem(key,JSON.stringify(value))};
const partClass=(image:number)=>`partPhoto part${Math.abs(image)%8}`;
const partStyle=(p:Product)=>p.imageUrl?{backgroundImage:`url(${p.imageUrl})`,backgroundSize:'contain',backgroundPosition:'center'}:undefined;
const partImageSrc=(p:Product)=>p.imageUrl||`/parts/part-${Math.abs(p.image)%8}.webp`;

function useShopData(){
 const [products,setProducts]=useState<Product[]>(defaults);
 const [cart,setCart]=useState<CartLine[]>([]);
 const [orders,setOrders]=useState<Order[]>([]);
 const normalize=(product:Product&{image?:number|string;imageIndex?:number})=>{const base=defaults.find(item=>item.id===product.id);const remoteImage=typeof product.image==='string'?product.image:product.imageUrl;return {...base,...product,image:Number(product.imageIndex??(typeof product.image==='number'?product.image:base?.image)??0),imageUrl:remoteImage||base?.imageUrl,brand:product.brand||base?.brand||'Berker Makine',currency:'TRY',condition:'new'} as Product};
 useEffect(()=>{setCart(load('zy-shop-cart',[]));fetch('/api/shop/products',{cache:'no-store'}).then(response=>response.ok?response.json():Promise.reject()).then((result:{products:Product[]})=>setProducts(result.products.map(normalize))).catch(()=>setProducts(defaults))},[]);
 const refreshOrders=()=>fetch('/api/shop/orders',{credentials:'same-origin',cache:'no-store'}).then(response=>response.ok?response.json():Promise.reject()).then((result:{orders:Order[]})=>setOrders(result.orders)).catch(()=>undefined);
 const updateProducts=async(v:Product[])=>{const previous=products;setProducts(v);try{const response=await fetch('/api/shop/products',{method:'PUT',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({products:v})});if(!response.ok)throw new Error('Ürünler kaydedilemedi');const result=await response.json() as {products:Product[]};setProducts(result.products.map(normalize))}catch(error){setProducts(previous);alert(error instanceof Error?error.message:'Ürünler kaydedilemedi')}};
 const updateCart=(v:CartLine[])=>{setCart(v);save('zy-shop-cart',v)};
 const updateOrders=async(v:Order[])=>{const changed=v.find(order=>orders.find(old=>old.id===order.id)?.status!==order.status);setOrders(v);if(changed)await fetch('/api/shop/orders',{method:'PATCH',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:changed.id,status:changed.status})}).catch(()=>undefined)};
 return{products,cart,orders,updateProducts,updateCart,updateOrders,refreshOrders};
}

export default function ShopSystem({page,slug}:{page:'shop'|'product'|'cart'|'checkout'|'admin';slug?:string}){
 const data=useShopData();
 const cartCount=data.cart.reduce((s,x)=>s+x.qty,0);
 const add=(id:number)=>{const old=data.cart.find(x=>x.id===id);data.updateCart(old?data.cart.map(x=>x.id===id?{...x,qty:x.qty+1}:x):[...data.cart,{id,qty:1}])};
 if(page==='admin')return <AdminGate><Admin {...data}/></AdminGate>;
 if(page==='cart'||page==='checkout')return <CartCheckout checkout={page==='checkout'} {...data}/>;
 if(page==='product')return <ProductDetail product={data.products.find(x=>x.slug===slug)||data.products[0]} add={add} cartCount={cartCount}/>;
 return <Shop products={data.products.filter(x=>x.active)} add={add} cart={data.cart} updateCart={data.updateCart} cartCount={cartCount}/>;
}

function Shop({products,add,cart,updateCart,cartCount}:{products:Product[];add:(id:number)=>void;cart:CartLine[];updateCart:(v:CartLine[])=>void;cartCount:number}){
 const [category,setCategory]=useState('Tümü');const [query,setQuery]=useState('');
 const [cartOpen,setCartOpen]=useState(false);
 useEffect(()=>{if(!cartOpen)return;const close=(event:KeyboardEvent)=>{if(event.key==='Escape')setCartOpen(false)};document.body.classList.add('cartDrawerOpen');window.addEventListener('keydown',close);return()=>{document.body.classList.remove('cartDrawerOpen');window.removeEventListener('keydown',close)}},[cartOpen]);
 const addAndOpen=(id:number)=>{add(id);setCartOpen(true)};
 const categories=['Tümü',...Array.from(new Set(products.map(x=>x.category)))];
 const shown=products.filter(x=>(category==='Tümü'||x.category===category)&&(`${x.name} ${x.sku}`.toLowerCase().includes(query.toLowerCase())));
 const cartProducts=cart.map(x=>({line:x,p:products.find(p=>p.id===x.id)})).filter(x=>x.p);
 const total=cartProducts.reduce((s,x)=>s+(x.p?.price||0)*x.line.qty,0);
 return <div className="shopPage">
   <section className="shopHero"><div><small>ORİJİNAL VE UYUMLU PARÇA ÇÖZÜMLERİ</small><h1>YEDEK PARÇA SHOP</h1><p>Zemin yıkama makineleriniz için güvenilir yedek parçaları keşfedin.</p><div className="shopSearch"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Ürün adı veya koduyla ara"/><button>ARA</button></div></div><div className="heroPart"><div className="shopHeroGlow"/><img src="/titan90-01.webp" alt="Ecoline Titan 90 zemin yıkama makinesi"/><span><small>BERKER MAKİNE</small><b>ECOLINE TITAN 90</b></span></div></section>
   <section className="darkBenefits benefits-parts">{[['♙','Model Uyumluluğu','Makinenize uygun parça kontrolü'],['◈','Parça Doğrulama','Sipariş öncesi teknik teyit'],['✹','Stok Bilgilendirmesi','Güncel stok durumunu öğrenin'],['⚙','Hızlı Sipariş','WhatsApp üzerinden kolay talep'],['◉','Teknik Destek','Montaj ve kullanım yönlendirmesi']].map(x=><div key={x[1]}><i aria-hidden="true">{x[0]}</i><span><b>{x[1]}</b><small>{x[2]}</small></span></div>)}</section>
  <div className="shopBar"><b>{shown.length} ürün listeleniyor</b><button className="shopCartButton" type="button" onClick={()=>setCartOpen(true)} aria-haspopup="dialog">Sepetim <span>{cartCount}</span></button></div>
  <section className="shopBody"><main><div className="categoryChips">{categories.map(x=><button className={category===x?'active':''} onClick={()=>setCategory(x)} key={x}>{x}</button>)}</div><div className="productGrid">{shown.map(p=><ProductCard key={p.id} p={p} add={addAndOpen}/>)}</div></main></section>
  {cartOpen&&<div className="cartDrawerBackdrop" onClick={()=>setCartOpen(false)}><aside className="cartDrawer" onClick={e=>e.stopPropagation()}><div className="cartHead"><h2>Sepetim ({cartCount})</h2><button type="button" onClick={()=>setCartOpen(false)} aria-label="Sepeti kapat">×</button></div>{cartProducts.length?cartProducts.map(({line,p})=><div className="miniCart drawerLine" key={line.id}><img className="partThumb" src={partImageSrc(p!)} alt=""/><div><b>{p!.name}</b><span>{money(p!.price)}</span><div className="drawerQty"><button onClick={()=>updateCart(line.qty>1?cart.map(x=>x.id===line.id?{...x,qty:x.qty-1}:x):cart.filter(x=>x.id!==line.id))}>−</button><span>{line.qty}</span><button onClick={()=>updateCart(cart.map(x=>x.id===line.id?{...x,qty:x.qty+1}:x))}>＋</button><button className="drawerRemove" onClick={()=>updateCart(cart.filter(x=>x.id!==line.id))}>Sil</button></div></div></div>):<p className="emptyCart">Sepetiniz henüz boş.</p>}<div className="cartTotal"><span>Ara toplam</span><b>{money(total)}</b></div>{cartProducts.length>0&&<><a className="shopPrimary whatsappOrder" href="/odeme">WHATSAPP’TAN SİPARİŞ VER</a><a className="drawerCartLink" href="/sepet">SEPET SAYFASINI AÇ</a></>}</aside></div>}
 </div>
}

function ProductCard({p,add}:{p:Product;add:(id:number)=>void}){return <article className="shopCard"><a href={`/yedek-parca/urun/${p.slug}`} className="partImageLink"><img src={partImageSrc(p)} alt={`${p.name} zemin yıkama makinesi yedek parçası`}/></a><small>{p.category}</small><h2><a href={`/yedek-parca/urun/${p.slug}`}>{p.name}</a></h2><p>Uyumlu: {p.compatibility}</p><span className={p.stock>0?'stock in':'stock out'}>{p.stock>0?'Stokta':'Tükendi'}</span><strong>{money(p.price)}</strong><button disabled={!p.stock} onClick={()=>add(p.id)}>🛒 SEPETE EKLE</button></article>}

function ProductDetail({product:p,add,cartCount}:{product:Product;add:(id:number)=>void;cartCount:number}){return <section className="productDetail"><div className="productPartImage"><img src={partImageSrc(p)} alt={`${p.name} ürün görseli`}/></div><article><small>{p.category} · {p.sku}</small><h1>{p.name}</h1><p>{p.description}</p><dl><div><dt>Marka</dt><dd>{p.brand}</dd></div><div><dt>Uyumluluk</dt><dd>{p.compatibility}</dd></div><div><dt>Stok</dt><dd>{p.stock} adet</dd></div><div><dt>Ürün durumu</dt><dd>Yeni</dd></div></dl><strong>{money(p.price)}</strong><button className="shopPrimary" onClick={()=>add(p.id)}>SEPETE EKLE</button><a href="/sepet">Sepete git ({cartCount}) →</a><em>Kesin uyumluluk sipariş öncesinde makine modeli üzerinden doğrulanmalıdır.</em></article></section>}

function CartCheckout({checkout,products,cart,orders,updateCart,updateOrders}:{checkout:boolean;products:Product[];cart:CartLine[];orders:Order[];updateCart:(v:CartLine[])=>void;updateOrders:(v:Order[])=>void}){
 const lines=cart.map(x=>({line:x,p:products.find(p=>p.id===x.id)})).filter(x=>x.p);const subtotal=lines.reduce((s,x)=>s+x.p!.price*x.line.qty,0);const [done,setDone]=useState('');const [coupon,setCoupon]=useState<{code:string;discount:number}|null>(null);const [couponMessage,setCouponMessage]=useState('');const total=subtotal*(1-(coupon?.discount||0)/100);
 const applyCoupon=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const code=String(new FormData(e.currentTarget).get('coupon')||'').trim();setCouponMessage('Kontrol ediliyor…');const response=await fetch('/api/shop/coupon',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code})});const result=await response.json() as {valid:boolean;code?:string;discount?:number;message?:string};if(result.valid&&result.code&&result.discount){setCoupon({code:result.code,discount:result.discount});setCouponMessage(`${result.code} uygulandı: %${result.discount} indirim`)}else{setCoupon(null);setCouponMessage(result.message||'Kupon geçersiz.')}};
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const popup=window.open('about:blank','_blank');const f=new FormData(e.currentTarget);const id=`ZY-${Date.now().toString().slice(-7)}`;const customer=String(f.get('customer'));const contact=String(f.get('contact'));const address=String(f.get('address'));const orderLines=lines.map(({line,p})=>({id:p!.id,name:p!.name,sku:p!.sku,qty:line.qty,unitPrice:p!.price}));const message=['Merhaba, zeminyikama.com Shop üzerinden sipariş vermek istiyorum.','',`Sipariş No: ${id}`,`Ad / Firma: ${customer}`,`İletişim: ${contact}`,`Teslimat Adresi: ${address}`,'','Ürünler:',...lines.map(({line,p})=>`• ${p!.name} (${p!.sku}) — ${line.qty} adet — ${money(p!.price*line.qty)}`),...(coupon?[``,`Kupon: ${coupon.code} (%${coupon.discount})`]:[]),'',`Toplam: ${money(total)}`,'','Ürün uyumluluğunu ve teslimat koşullarını teyit eder misiniz?'].join('\n');try{const response=await fetch('/api/shop/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,customer,contact,address,total,lines:orderLines})});if(!response.ok)throw new Error('Sipariş kaydı oluşturulamadı.');const whatsapp=`https://wa.me/905375223946?text=${encodeURIComponent(message)}`;if(popup)popup.location.href=whatsapp;else window.location.href=whatsapp;updateCart([]);setDone(id)}catch(error){popup?.close();alert(error instanceof Error?error.message:'Sipariş kaydı oluşturulamadı.')}};
if(done)return <section className="orderDone"><b>✓</b><h1>Siparişiniz oluşturuldu.</h1><p>Sipariş numaranız: <strong>{done}</strong></p><a href="/yedek-parca">YEDEK PARÇAYA DÖN</a></section>;
 return <section className="cartPage"><div><small>{checkout?'TESLİMAT VE WHATSAPP SİPARİŞİ':'ALIŞVERİŞ SEPETİ'}</small><h1>{checkout?'Sipariş bilgilerinizi girin':'Sepetiniz'}</h1>{!checkout?lines.map(({line,p})=><article className="cartRow" key={line.id}><img className="partThumb" src={partImageSrc(p!)} alt=""/><div><h2>{p!.name}</h2><p>{p!.sku}</p></div><input type="number" min="1" value={line.qty} onChange={e=>updateCart(cart.map(x=>x.id===line.id?{...x,qty:Number(e.target.value)}:x))}/><strong>{money(p!.price*line.qty)}</strong><button onClick={()=>updateCart(cart.filter(x=>x.id!==line.id))}>×</button></article>):<><form className="couponForm" onSubmit={applyCoupon}><label>İndirim kuponu<input name="coupon" placeholder="KUPON KODU" required/></label><button type="submit">UYGULA</button>{couponMessage&&<b>{couponMessage}</b>}</form><form className="checkoutForm" onSubmit={submit}><label>Ad Soyad / Firma<input name="customer" required/></label><label>Telefon<input name="contact" inputMode="tel" required/></label><label className="wide">Teslimat adresi<textarea name="address" rows={4} required/></label><p className="wide whatsappInfo">Sipariş özetiniz WhatsApp’ta hazır mesaj olarak açılır ve yönetim paneline kaydedilir.</p><button className="shopPrimary whatsappOrder" type="submit">WHATSAPP’TAN SİPARİŞ VER</button></form></>}</div><aside><h2>Sipariş Özeti</h2>{lines.map(x=><p key={x.line.id}><span>{x.p!.name} × {x.line.qty}</span><b>{money(x.p!.price*x.line.qty)}</b></p>)}{coupon&&<p><span>Kupon ({coupon.code})</span><b>−%{coupon.discount}</b></p>}<div><span>Toplam</span><strong>{money(total)}</strong></div>{!checkout&&<a className="shopPrimary whatsappOrder" href="/odeme">WHATSAPP’TAN SİPARİŞ VER</a>}</aside></section>
}

function MachineManager(){
 const empty:AdminMachine={slug:'',name:'',kind:'Binicili',fit:'',area:'',image:'',description:''};
 const [state,setState]=useState<MachineAdminState>({hidden:[],custom:[]});
 const [draft,setDraft]=useState<AdminMachine>(empty);
 const [adding,setAdding]=useState(false);
 const [editingSlug,setEditingSlug]=useState('');
 const [categories,setCategories]=useState<string[]>(['Binicili','İtmeli','Akülü','Süpürücü']);
 const [newCategory,setNewCategory]=useState('');
 const [imageError,setImageError]=useState('');
 useEffect(()=>{const stored=load<MachineAdminState>(machineAdminKey,{hidden:[],custom:[]});setState({hidden:Array.isArray(stored.hidden)?stored.hidden:[],custom:Array.isArray(stored.custom)?stored.custom:[]});setCategories(load('zy-machine-categories',['Binicili','İtmeli','Akülü','Süpürücü']))},[]);
 const persist=(next:MachineAdminState)=>{setState(next);save(machineAdminKey,next);window.dispatchEvent(new Event('zy-machines-updated'))};
 const visible=[...baseMachines.filter(x=>!state.hidden.includes(x.slug)).map(x=>state.custom.find(c=>c.slug===x.slug)||x),...state.custom.filter(x=>!baseMachines.some(b=>b.slug===x.slug))];
 const remove=(slug:string)=>{const isBase=baseMachines.some(x=>x.slug===slug);persist({hidden:isBase?[...new Set([...state.hidden,slug])]:state.hidden,custom:state.custom.filter(x=>x.slug!==slug)})};
 const restore=(slug:string)=>persist({...state,hidden:state.hidden.filter(x=>x!==slug)});
 const chooseImage=(file?:File)=>{if(!file)return;if(file.size>20*1024*1024){setImageError('Görsel 20 MB’den küçük olmalıdır.');return}setImageError('Görsel optimize ediliyor…');const url=URL.createObjectURL(file);const img=new Image();img.onload=()=>{const max=1600;const scale=Math.min(1,max/Math.max(img.width,img.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.width*scale));canvas.height=Math.max(1,Math.round(img.height*scale));const ctx=canvas.getContext('2d');if(!ctx){setImageError('Görsel işlenemedi.');URL.revokeObjectURL(url);return}ctx.drawImage(img,0,0,canvas.width,canvas.height);setDraft(x=>({...x,image:canvas.toDataURL('image/webp',.82)}));setImageError('');URL.revokeObjectURL(url)};img.onerror=()=>{setImageError('Görsel okunamadı. PNG, JPG veya WEBP deneyin.');URL.revokeObjectURL(url)};img.src=url};
 const openEditor=(item?:AdminMachine)=>{setDraft(item?{...item}:empty);setEditingSlug(item?.slug||'');setAdding(true);setImageError('')};
 const submit=(e:FormEvent)=>{e.preventDefault();const slug=editingSlug||draft.slug||draft.name.toLocaleLowerCase('tr-TR').replace(/[^a-z0-9çğıöşü]+/g,'-').replace(/^-|-$/g,'');persist({...state,hidden:state.hidden.filter(x=>x!==slug),custom:[...state.custom.filter(x=>x.slug!==slug),{...draft,slug}]});setDraft(empty);setEditingSlug('');setAdding(false)};
 const addCategory=()=>{const value=newCategory.trim();if(!value||categories.includes(value))return;const next=[...categories,value];setCategories(next);save('zy-machine-categories',next);setNewCategory('')};
 const deleteCategory=(value:string)=>{if(visible.some(x=>x.kind===value)){alert('Bu kategoride makine bulunuyor. Önce makinelerin kategorisini değiştirin.');return}const next=categories.filter(x=>x!==value);setCategories(next);save('zy-machine-categories',next)};
 return <section className="machineManager"><div className="machineManagerHead"><div><h2>Makine Modelleri</h2><p>Bir modele dokunarak ayrıntılarını açabilir, düzenleyebilir veya kaldırabilirsiniz.</p></div><button onClick={()=>openEditor()}>＋ YENİ MAKİNE EKLE</button></div><section className="machineCategoryAdmin"><div><input value={newCategory} onChange={e=>setNewCategory(e.target.value)} placeholder="Yeni kategori adı"/><button type="button" onClick={addCategory}>KATEGORİ EKLE</button></div><nav>{categories.map(x=><span key={x}>{x}<button type="button" aria-label={`${x} kategorisini sil`} onClick={()=>deleteCategory(x)}>×</button></span>)}</nav></section>{adding&&<form className="machineAdminForm" onSubmit={submit}><h3 className="wide">{editingSlug?'Makineyi Düzenle':'Yeni Makine Ekle'}</h3><label className="machineImageUpload"><span>Vitrin görseli</span>{draft.image?<img src={draft.image} alt="Seçilen makine görseli"/>:<div>GÖRSEL SEÇİLMEDİ</div>}<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>chooseImage(e.target.files?.[0])}/><b>Bilgisayardan görsel seç</b><small>PNG, JPG veya WEBP · En fazla 20 MB</small>{imageError&&<em>{imageError}</em>}</label><label>Model adı<input required value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>Kategori<select value={draft.kind} onChange={e=>setDraft({...draft,kind:e.target.value})}>{categories.map(x=><option key={x}>{x}</option>)}</select></label><label>Kısa açıklama<input required value={draft.fit} onChange={e=>setDraft({...draft,fit:e.target.value})}/></label><label>Kullanım alanı<input required value={draft.area} onChange={e=>setDraft({...draft,area:e.target.value})}/></label><label className="wide">Ürün açıklaması<textarea rows={5} value={draft.description||''} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><div className="wide editActions"><button type="button" onClick={()=>{setAdding(false);setEditingSlug('')}}>İptal</button><button type="submit">Makineyi Kaydet</button></div></form>}<div className="machineAdminGrid">{visible.map(x=><article key={x.slug} className="machineAdminItem" onClick={()=>openEditor(x)}>{x.image?<img src={x.image} alt=""/>:<div className="machinePlaceholder">GÖRSEL</div>}<div><small>{x.kind}</small><h3>{x.name}</h3><p>{x.fit}</p><b>AYRINTILARI AÇ / DÜZENLE →</b></div><button onClick={e=>{e.stopPropagation();if(confirm(`${x.name} kaldırılsın mı?`))remove(x.slug)}}>KALDIR</button></article>)}</div>{state.hidden.length>0&&<div className="hiddenMachines"><h3>Kaldırılan modeller</h3>{state.hidden.map(slug=><button key={slug} onClick={()=>restore(slug)}>↻ {baseMachines.find(x=>x.slug===slug)?.name||slug} modelini geri getir</button>)}</div>}</section>
}

function AdminGate({children}:{children:React.ReactNode}){
 const [status,setStatus]=useState<'checking'|'guest'|'authenticated'>('checking');
 const [error,setError]=useState('');
 const [submitting,setSubmitting]=useState(false);
 useEffect(()=>{let active=true;fetch('/api/admin/session',{credentials:'same-origin',cache:'no-store'}).then(response=>{if(active)setStatus(response.ok?'authenticated':'guest')}).catch(()=>{if(active)setStatus('guest')});return()=>{active=false}},[]);
 const login=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setSubmitting(true);setError('');const form=event.currentTarget;const data=new FormData(form);try{const response=await fetch('/api/admin/login',{method:'POST',credentials:'same-origin',cache:'no-store',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:String(data.get('username')||''),password:String(data.get('password')||'')})});if(!response.ok){let message='Giriş yapılamadı.';try{message=(await response.json() as {message?:string}).message||message}catch{}setError(message);return}form.reset();setStatus('authenticated')}catch{setError('Bağlantı kurulamadı. Lütfen tekrar deneyin.')}finally{setSubmitting(false)}};
 const logout=async()=>{await fetch('/api/admin/logout',{method:'POST',credentials:'same-origin'}).catch(()=>undefined);setStatus('guest')};
 if(status==='checking')return <main className="adminLogin"><form><div className="adminLoginLogo" aria-label="Zeminyikama.com"/><small>GÜVENLİ YÖNETİM</small><h1>Oturum kontrol ediliyor</h1><p>Lütfen kısa bir süre bekleyin.</p></form></main>;
 if(status==='authenticated')return <div className="adminAuthenticated">{children}<button className="adminLogout" type="button" onClick={logout}>GÜVENLİ ÇIKIŞ</button></div>;
 return <main className="adminLogin"><form onSubmit={login}><div className="adminLoginLogo" aria-label="Zeminyikama.com"/><small>GÜVENLİ YÖNETİM</small><h1>Yönetim paneli girişi</h1><p>Yönetim bilgileri yalnızca sunucuda doğrulanır ve hiçbir parola tarayıcıya gönderilmez.</p><label>Kullanıcı adı<input name="username" autoComplete="username" maxLength={100} required autoFocus/></label><label>Parola<input name="password" type="password" autoComplete="current-password" maxLength={256} required/></label>{error&&<b role="alert">{error}</b>}<button type="submit" disabled={submitting}>{submitting?'DOĞRULANIYOR…':'GÜVENLİ GİRİŞ'}</button><a href="/yedek-parca">← Yedek parçaya dön</a></form></main>
}

function Admin({products,orders,updateProducts,updateOrders,refreshOrders}:{products:Product[];orders:Order[];updateProducts:(v:Product[])=>void;updateOrders:(v:Order[])=>void;refreshOrders:()=>Promise<void>}){
 const empty:Product={id:0,slug:'',name:'',sku:'',category:'Fırçalar',compatibility:'',price:0,currency:'TRY',stock:0,image:0,active:true,description:'',brand:'Berker Makine',condition:'new'};
 const [draft,setDraft]=useState<Product>(empty);const [editing,setEditing]=useState(false);const [tab,setTab]=useState('Ürünler');const [newCategory,setNewCategory]=useState('');const [customCategories,setCustomCategories]=useState<string[]>([]);const [imageError,setImageError]=useState('');
 const [settings,setSettings]=useState({storeName:'Zemin Yıkama Yedek Parça Shop',phone:'',whatsapp:'',email:'',shipping:'150'});const [settingsSaved,setSettingsSaved]=useState(false);
 const [brands,setBrands]=useState<string[]>([]);const [newBrand,setNewBrand]=useState('');const [coupons,setCoupons]=useState<{code:string;discount:number;active:boolean}[]>([]);const [newCoupon,setNewCoupon]=useState('');
 const persistConfig=async(overrides:Partial<{settings:typeof settings;brands:string[];coupons:typeof coupons;categories:string[]}>)=>{const config={settings:overrides.settings||settings,brands:overrides.brands||brands,coupons:overrides.coupons||coupons,categories:overrides.categories||customCategories};const response=await fetch('/api/shop/admin-state',{method:'PUT',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({config})});if(!response.ok)alert('Değişiklik kaydedilemedi. Lütfen tekrar deneyin.')};
 useEffect(()=>{refreshOrders();fetch('/api/shop/admin-state',{credentials:'same-origin',cache:'no-store'}).then(response=>response.ok?response.json():Promise.reject()).then((result:{config:{settings:typeof settings;brands:string[];coupons:typeof coupons;categories:string[]}})=>{setSettings(result.config.settings);setBrands(result.config.brands);setCoupons(result.config.coupons);setCustomCategories(result.config.categories)}).catch(()=>undefined)},[]);
 const active=products.filter(x=>x.active).length;const low=products.filter(x=>x.stock<10).length;const categories=Array.from(new Set([...products.map(x=>x.category),...customCategories])).sort();
 const chooseImage=(file?:File)=>{if(!file)return;if(file.size>20*1024*1024){setImageError('Görsel 20 MB’den küçük olmalıdır.');return}setImageError('Görsel optimize edilip sunucuya yükleniyor…');const url=URL.createObjectURL(file);const img=new Image();img.onload=()=>{const max=1600;const scale=Math.min(1,max/Math.max(img.width,img.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.width*scale));canvas.height=Math.max(1,Math.round(img.height*scale));const ctx=canvas.getContext('2d');if(!ctx){setImageError('Görsel işlenemedi.');URL.revokeObjectURL(url);return}ctx.drawImage(img,0,0,canvas.width,canvas.height);canvas.toBlob(async blob=>{URL.revokeObjectURL(url);if(!blob){setImageError('Görsel işlenemedi.');return}try{const form=new FormData();form.append('file',new File([blob],'product.webp',{type:'image/webp'}));const response=await fetch('/api/shop/images',{method:'POST',credentials:'same-origin',body:form});const result=await response.json() as {url?:string;message?:string};if(!response.ok||!result.url)throw new Error(result.message||'Görsel yüklenemedi.');setDraft(x=>({...x,imageUrl:result.url}));setImageError('')}catch(error){setImageError(error instanceof Error?error.message:'Görsel yüklenemedi.')}},'image/webp',.84)};img.onerror=()=>{setImageError('Bu görsel okunamadı. PNG, JPG veya WEBP deneyin.');URL.revokeObjectURL(url)};img.src=url};
 const submit=(e:FormEvent)=>{e.preventDefault();const item={...draft,id:draft.id||Date.now(),slug:draft.slug||draft.name.toLocaleLowerCase('tr-TR').replace(/[^a-z0-9çğıöşü]+/g,'-').replace(/^-|-$/g,'')};updateProducts(draft.id?products.map(x=>x.id===draft.id?item:x):[item,...products]);setDraft(empty);setEditing(false)};
 const nav=['Kontrol Paneli','Siparişler','Ürünler','Kategoriler','Markalar','Stok','Müşteriler','Raporlar','Kuponlar','Ayarlar'];
 const editor=editing&&<form className="adminEdit" onSubmit={submit}><h2>{draft.id?'Ürün Düzenle':'Yeni Ürün Ekle'}</h2><label className="imageUpload"><span>Ürün görseli</span><div className={partClass(draft.image)} style={partStyle(draft)}/><input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>chooseImage(e.target.files?.[0])}/><b>Bilgisayardan görsel seç</b><small>PNG, JPG veya WEBP · En fazla 20 MB · Otomatik optimize edilir</small>{imageError&&<em>{imageError}</em>}</label>{draft.imageUrl&&<button className="removeImage" type="button" onClick={()=>setDraft({...draft,imageUrl:undefined})}>Yüklenen görseli kaldır</button>}<label>Ürün adı<input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})} required/></label><label>SKU<input value={draft.sku} onChange={e=>setDraft({...draft,sku:e.target.value})} required/></label><label>Marka<input value={draft.brand} onChange={e=>setDraft({...draft,brand:e.target.value})} required/></label><label>Kategori<select value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})}>{categories.map(x=><option key={x}>{x}</option>)}</select></label><div><label>Stok<input type="number" min="0" value={draft.stock} onChange={e=>setDraft({...draft,stock:Number(e.target.value)})}/></label><label>Fiyat<input type="number" min="0" step="0.01" value={draft.price} onChange={e=>setDraft({...draft,price:Number(e.target.value)})}/></label></div><label>Uyumluluk<input value={draft.compatibility} onChange={e=>setDraft({...draft,compatibility:e.target.value})}/></label><label>Hazır görsel kullan<select value={draft.image} onChange={e=>setDraft({...draft,image:Number(e.target.value),imageUrl:undefined})}>{defaults.map((x,i)=><option value={i} key={i}>Yedek parça görseli {i+1}</option>)}</select></label><label>Açıklama<textarea rows={4} value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><label className="adminCheck"><input type="checkbox" checked={draft.active} onChange={e=>setDraft({...draft,active:e.target.checked})}/> Ürün yayında</label><div className="editActions"><button type="button" onClick={()=>setEditing(false)}>İptal</button><button type="submit">Kaydet</button></div></form>;
 return <div className="adminApp"><aside className="adminSide"><div className="adminBrand">zemin<span>yıkama.com</span></div>{nav.map((x,i)=><button className={tab===x?'active':''} onClick={()=>{setTab(x);setEditing(false)}} key={x}>{['⌂','▣','▤','◇','▦','⚙'][i]} {x}</button>)}<a href="/shop">← Shop’a dön</a></aside><main className="adminMain"><header><div><small>KONTROL PANELİ / {tab.toUpperCase()}</small><h1>{tab==='Kontrol Paneli'?'GENEL DURUM':tab.toUpperCase()}</h1></div>{tab==='Ürünler'&&<button onClick={()=>{setDraft(empty);setEditing(true)}}>＋ YENİ ÜRÜN EKLE</button>}</header><section className="adminStats"><article><span>Toplam Ürün</span><b>{products.length}</b></article><article><span>Düşük Stoklu</span><b>{low}</b></article><article><span>Yeni Sipariş</span><b>{orders.filter(x=>x.status==='Yeni sipariş').length}</b></article><article><span>Aktif Ürün</span><b>{active}</b></article></section>
 {tab==='Kontrol Paneli'&&<section className="adminPanels"><article><h2>Mağaza Özeti</h2><p>Shop’ta {active} aktif ürün ve {categories.length} kategori bulunuyor.</p><button onClick={()=>setTab('Ürünler')}>Ürünleri yönet</button></article><article><h2>Stok Uyarısı</h2><p>{low} ürünün stoğu 10 adedin altında.</p><button onClick={()=>setTab('Stok')}>Stokları kontrol et</button></article><article><h2>Siparişler</h2><p>{orders.length} sipariş kaydı bulunuyor.</p><button onClick={()=>setTab('Siparişler')}>Siparişleri aç</button></article></section>}
 {tab==='Ürünler'&&<section className="adminWorkspace"><div className="adminTable"><div className="tableTitle"><h2>Ürünler</h2><span>{products.length} kayıt</span></div>{products.map(p=><article key={p.id}><div className={partClass(p.image)} style={partStyle(p)}/><div><b>{p.name}</b><small>{p.sku}</small></div><span>{p.category}</span><strong className={p.stock<10?'low':''}>{p.stock}</strong><b>{money(p.price)}</b><em className={p.active?'on':'off'}>{p.active?'Aktif':'Pasif'}</em><button aria-label="Düzenle" onClick={()=>{setDraft(p);setEditing(true)}}>✎</button><button aria-label="Sil" onClick={()=>{if(confirm(`${p.name} silinsin mi?`))updateProducts(products.filter(x=>x.id!==p.id))}}>×</button></article>)}</div>{editor}</section>}
 {tab==='Siparişler'&&<section className="adminList"><h2>Siparişler</h2>{orders.length?orders.map(o=><article key={o.id}><div><b>Sipariş: {o.id}</b><span><strong>{o.customer}</strong> · {o.contact}</span><small>{o.address}</small>{o.lines?.map(line=><small key={`${o.id}-${line.id}`}>{line.name} · {line.qty} adet · {money(line.unitPrice*line.qty)}</small>)}<small>{new Date(o.createdAt).toLocaleString('tr-TR')}</small></div><strong>{money(o.total)}</strong><select value={o.status} onChange={e=>updateOrders(orders.map(x=>x.id===o.id?{...x,status:e.target.value}:x))}><option>WhatsApp siparişi</option><option>Yeni sipariş</option><option>Hazırlanıyor</option><option>Kargoya verildi</option><option>Tamamlandı</option><option>İptal</option></select></article>):<p className="adminEmpty">Henüz sipariş bulunmuyor. Shop üzerinden oluşturulan siparişler burada görünecek.</p>}</section>}
 {tab==='Kategoriler'&&<section className="adminList"><div className="tableTitle"><h2>Kategoriler</h2><form onSubmit={e=>{e.preventDefault();const name=newCategory.trim();if(name&&!categories.includes(name)){const next=[...customCategories,name];setCustomCategories(next);persistConfig({categories:next})}setNewCategory('')}}><input aria-label="Yeni kategori" value={newCategory} onChange={e=>setNewCategory(e.target.value)} placeholder="Yeni kategori adı" required/><button>EKLE</button></form></div>{categories.map(c=><article key={c}><div><b>{c}</b><span>{products.filter(p=>p.category===c).length} ürün</span></div><button onClick={()=>{setDraft({...empty,category:c});setEditing(true);setTab('Ürünler')}}>Bu kategoriye ürün ekle</button><button disabled={products.some(p=>p.category===c)} title="İçinde ürün bulunan kategori silinemez" onClick={()=>{const next=customCategories.filter(x=>x!==c);setCustomCategories(next);persistConfig({categories:next})}}>Sil</button></article>)}</section>}
 {tab==='Stok'&&<section className="adminList"><h2>Hızlı Stok Yönetimi</h2>{products.map(p=><article key={p.id}><div><b>{p.name}</b><span>{p.sku}</span></div><strong className={p.stock<10?'low':''}>{p.stock} adet</strong><div className="stockButtons"><button onClick={()=>updateProducts(products.map(x=>x.id===p.id?{...x,stock:Math.max(0,x.stock-1)}:x))}>−</button><button onClick={()=>updateProducts(products.map(x=>x.id===p.id?{...x,stock:x.stock+1}:x))}>＋</button></div></article>)}</section>}
 {tab==='Markalar'&&<section className="adminList"><div className="tableTitle"><h2>Markalar</h2><form onSubmit={e=>{e.preventDefault();if(newBrand&&!brands.includes(newBrand)){const next=[...brands,newBrand];setBrands(next);persistConfig({brands:next})}setNewBrand('')}}><input aria-label="Yeni marka" value={newBrand} onChange={e=>setNewBrand(e.target.value)} placeholder="Marka adı"/><button>EKLE</button></form></div>{brands.map(b=><article key={b}><div><b>{b}</b><span>Uyumluluk ve filtrelemede kullanılabilir</span></div><button onClick={()=>{const next=brands.filter(x=>x!==b);setBrands(next);persistConfig({brands:next})}}>Sil</button></article>)}</section>}
 {tab==='Müşteriler'&&<section className="adminList"><h2>Müşteriler</h2>{orders.length?Array.from(new Map(orders.map(o=>[o.contact,o])).values()).map(o=><article key={o.contact}><div><b>{o.customer}</b><span>{o.contact}</span><small>{o.address}</small></div><strong>{orders.filter(x=>x.contact===o.contact).length} sipariş</strong></article>):<p className="adminEmpty">Sipariş veren müşteriler otomatik olarak burada listelenecek.</p>}</section>}
 {tab==='Raporlar'&&<section className="adminPanels"><article><h2>Toplam Satış</h2><p>Tamamlanan ve açık siparişlerin toplam değeri.</p><b>{money(orders.reduce((s,o)=>s+o.total,0))}</b></article><article><h2>Ortalama Sepet</h2><p>Sipariş başına ortalama tutar.</p><b>{money(orders.length?orders.reduce((s,o)=>s+o.total,0)/orders.length:0)}</b></article><article><h2>Stok Değeri</h2><p>Mevcut ürün stoklarının tahmini satış değeri.</p><b>{money(products.reduce((s,p)=>s+p.price*p.stock,0))}</b></article></section>}
 {tab==='Kuponlar'&&<section className="adminList"><div className="tableTitle"><h2>İndirim Kuponları</h2><form onSubmit={e=>{e.preventDefault();if(newCoupon){const next=[...coupons,{code:newCoupon.toUpperCase(),discount:10,active:true}];setCoupons(next);persistConfig({coupons:next})}setNewCoupon('')}}><input aria-label="Yeni kupon" value={newCoupon} onChange={e=>setNewCoupon(e.target.value)} placeholder="KUPON KODU"/><button>OLUŞTUR</button></form></div>{coupons.length?coupons.map(c=><article key={c.code}><div><b>{c.code}</b><label>İndirim oranı (%)<input type="number" min="1" max="90" value={c.discount} onChange={e=>{const next=coupons.map(x=>x.code===c.code?{...x,discount:Number(e.target.value)}:x);setCoupons(next)}} onBlur={()=>persistConfig({coupons})}/></label></div><button onClick={()=>{const next=coupons.map(x=>x.code===c.code?{...x,active:!x.active}:x);setCoupons(next);persistConfig({coupons:next})}}>{c.active?'Pasife al':'Aktifleştir'}</button><button onClick={()=>{const next=coupons.filter(x=>x.code!==c.code);setCoupons(next);persistConfig({coupons:next})}}>Sil</button></article>):<p className="adminEmpty">Henüz kupon oluşturulmadı.</p>}</section>}
 {tab==='Ayarlar'&&<form className="adminSettings" onSubmit={e=>{e.preventDefault();persistConfig({settings});setSettingsSaved(true);setTimeout(()=>setSettingsSaved(false),2500)}}><h2>Shop Ayarları</h2><label>Mağaza adı<input value={settings.storeName} onChange={e=>setSettings({...settings,storeName:e.target.value})}/></label><label>Telefon<input value={settings.phone} onChange={e=>setSettings({...settings,phone:e.target.value})} placeholder="05xx xxx xx xx"/></label><label>WhatsApp<input value={settings.whatsapp} onChange={e=>setSettings({...settings,whatsapp:e.target.value})} placeholder="905xx..."/></label><label>E-posta<input value={settings.email} onChange={e=>setSettings({...settings,email:e.target.value})}/></label><label>Ücretsiz kargo limiti<input type="number" value={settings.shipping} onChange={e=>setSettings({...settings,shipping:e.target.value})}/></label><button className="shopPrimary">AYARLARI KAYDET</button>{settingsSaved&&<b className="saveNotice">✓ Ayarlar kaydedildi</b>}</form>}
 </main></div>
}
