'use client';

import {FormEvent,useEffect,useMemo,useState} from 'react';

type Product={id:number;slug:string;name:string;sku:string;category:string;compatibility:string;price:number;stock:number;image:number;imageUrl?:string;active:boolean;description:string};
type CartLine={id:number;qty:number};
type Order={id:string;customer:string;contact:string;address:string;total:number;status:string;createdAt:string};
type AdminMachine={slug:string;name:string;kind:string;fit:string;area:string;image?:string;description?:string};
type MachineAdminState={hidden:string[];custom:AdminMachine[]};
const machineAdminKey='zy-machine-admin';
const baseMachines:AdminMachine[]=[
 {slug:'ecoline-b250-binicili-zemin-temizleme-otomati',name:'Berker Ecoline B250',kind:'Binicili',fit:'Geniş alanlarda yüksek kapasiteli temizlik',area:'AVM, fabrika, depo ve otopark',image:'/b250-showcase.webp'},
 {slug:'ecoline-b140-binicili-zemin-temizleme-makinasi',name:'Berker Ecoline B140',kind:'Binicili',fit:'Dar ve kalabalık alanlarda çevik temizlik',area:'Okul, hastane, market ve otel',image:'/b140-showcase.webp'},
 {slug:'ecoline-b60-zemin-temizleme-makinasi',name:'Berker Ecoline B60',kind:'İtmeli',fit:'Günlük profesyonel temizlik için kompakt çözüm',area:'AVM, fabrika, hastane ve depo',image:'/b60-showcase.webp'},
 {slug:'berker-ecoline-c70-binicili-zemin-yikama-makinasi',name:'Berker Ecoline C70',kind:'Binicili',fit:'Çift fırçalı yüksek verimli çözüm',area:'Süpermarket, fabrika ve depo',image:'/c70-showcase.webp'},
 {slug:'berker-ecoline-b45-akulu-itmeli-zemin-otomati',name:'Berker Ecoline B45',kind:'İtmeli',fit:'Orta ölçekli alanlar için pratik temizlik',area:'Fabrika, depo, okul ve ofis',image:'/b45-showcase.webp'},
];

const defaults:Product[]=[
 {id:1,slug:'firca-diski-17-orta-sert',name:'Fırça Diski – 17” Orta Sert',sku:'FD17-OS',category:'Fırçalar',compatibility:'Nilfisk SC500 / SC550',price:1250,stock:34,image:0,active:true,description:'Günlük zemin temizliği için orta sertlikte profesyonel fırça diski.'},
 {id:2,slug:'silecek-lastigi-on-890mm',name:'Silecek Lastiği – Ön 890 mm',sku:'SL-890-O',category:'Silecek Lastikleri',compatibility:'Tennant T300 / T500',price:620,stock:12,image:1,active:true,description:'Temiz ve iz bırakmayan su toplama performansı için dayanıklı ön lastik.'},
 {id:3,slug:'vakum-motoru-36v-550w',name:'Vakum Motoru – 36V 550W',sku:'VM-36V-550',category:'Vakum Motorları',compatibility:'Nilfisk BA / CA Serisi',price:3750,stock:8,image:2,active:true,description:'Profesyonel zemin yıkama makineleri için kompakt vakum motoru.'},
 {id:4,slug:'aku-sarj-cihazi-24v-15a',name:'Akü Şarj Cihazı – 24V 15A',sku:'SC-24V-15A',category:'Aküler & Şarj',compatibility:'Tüm 24V akü grupları',price:4950,stock:15,image:3,active:true,description:'Makine akülerinin düzenli şarj döngüsü için endüstriyel şarj cihazı.'},
 {id:5,slug:'emis-hortumu-38mm',name:'Emiş Hortumu – 38 mm',sku:'EH-38',category:'Hortumlar',compatibility:'Nilfisk / Tennant / Hako',price:480,stock:22,image:4,active:true,description:'Esnek, dayanıklı ve profesyonel kullanıma uygun emiş hortumu.'},
 {id:6,slug:'vakum-filtresi-polyester',name:'Vakum Filtresi – Polyester',sku:'VF-POL',category:'Filtreler',compatibility:'Nilfisk BA 551 / BA 611',price:350,stock:19,image:5,active:true,description:'Toz ve kir tutma verimini destekleyen değiştirilebilir polyester filtre.'},
 {id:7,slug:'jel-aku-12v-105ah',name:'Jel Akü – 12V 105Ah',sku:'AKU-12-105',category:'Aküler & Şarj',compatibility:'Uyumluluk teklif sırasında teyit edilir',price:6800,stock:6,image:6,active:true,description:'Zemin temizleme makineleri için bakım gereksinimi düşük jel akü.'},
 {id:8,slug:'pad-tutucu-17',name:'Pad Tutucu – 17”',sku:'PT-17',category:'Pad Tutucular',compatibility:'Nilfisk / Tennant',price:950,stock:27,image:7,active:true,description:'Profesyonel yüzey bakım pedleriyle kullanılabilen sağlam pad tutucu.'},
];

const money=(n:number)=>new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY'}).format(n);
const load=<T,>(key:string,fallback:T):T=>{if(typeof window==='undefined')return fallback;try{return JSON.parse(localStorage.getItem(key)||'null')||fallback}catch{return fallback}};
const save=(key:string,value:unknown)=>{if(typeof window!=='undefined')localStorage.setItem(key,JSON.stringify(value))};
const partClass=(image:number)=>`partPhoto part${Math.abs(image)%8}`;
const partStyle=(p:Product)=>p.imageUrl?{backgroundImage:`url(${p.imageUrl})`,backgroundSize:'contain',backgroundPosition:'center'}:undefined;
const partImageSrc=(p:Product)=>p.imageUrl||`/parts/part-${Math.abs(p.image)%8}.webp`;

function useShopData(){
 const [products,setProducts]=useState<Product[]>(defaults);
 const [cart,setCart]=useState<CartLine[]>([]);
 const [orders,setOrders]=useState<Order[]>([]);
 useEffect(()=>{setProducts(load('zy-shop-products',defaults));setCart(load('zy-shop-cart',[]));setOrders(load('zy-shop-orders',[]))},[]);
 const updateProducts=(v:Product[])=>{setProducts(v);save('zy-shop-products',v)};
 const updateCart=(v:CartLine[])=>{setCart(v);save('zy-shop-cart',v)};
 const updateOrders=(v:Order[])=>{setOrders(v);save('zy-shop-orders',v)};
 return{products,cart,orders,updateProducts,updateCart,updateOrders};
}

export default function ShopSystem({page,slug}:{page:'shop'|'product'|'cart'|'checkout'|'admin';slug?:string}){
 const data=useShopData();
 const cartCount=data.cart.reduce((s,x)=>s+x.qty,0);
 const add=(id:number)=>{const old=data.cart.find(x=>x.id===id);data.updateCart(old?data.cart.map(x=>x.id===id?{...x,qty:x.qty+1}:x):[...data.cart,{id,qty:1}])};
 if(page==='admin')return <AdminGate><Admin {...data}/></AdminGate>;
 if(page==='cart'||page==='checkout')return <CartCheckout checkout={page==='checkout'} {...data}/>;
 if(page==='product')return <ProductDetail product={data.products.find(x=>x.slug===slug)||data.products[0]} add={add} cartCount={cartCount}/>;
 return <Shop products={data.products.filter(x=>x.active)} add={add} cart={data.cart} updateCart={data.updateCart} cartCount={cartCount}/>;
}

function Shop({products,add,cart,updateCart,cartCount}:{products:Product[];add:(id:number)=>void;cart:CartLine[];updateCart:(v:CartLine[])=>void;cartCount:number}){
 const [category,setCategory]=useState('Tümü');const [query,setQuery]=useState('');
 const [cartOpen,setCartOpen]=useState(false);
 useEffect(()=>{if(!cartOpen)return;const close=(event:KeyboardEvent)=>{if(event.key==='Escape')setCartOpen(false)};document.body.classList.add('cartDrawerOpen');window.addEventListener('keydown',close);return()=>{document.body.classList.remove('cartDrawerOpen');window.removeEventListener('keydown',close)}},[cartOpen]);
 const addAndOpen=(id:number)=>{add(id);setCartOpen(true)};
 const categories=['Tümü',...Array.from(new Set(products.map(x=>x.category)))];
 const shown=products.filter(x=>(category==='Tümü'||x.category===category)&&(`${x.name} ${x.sku}`.toLowerCase().includes(query.toLowerCase())));
 const cartProducts=cart.map(x=>({line:x,p:products.find(p=>p.id===x.id)})).filter(x=>x.p);
 const total=cartProducts.reduce((s,x)=>s+(x.p?.price||0)*x.line.qty,0);
 return <div className="shopPage">
  <section className="shopHero"><div><small>ORİJİNAL VE UYUMLU PARÇA ÇÖZÜMLERİ</small><h1>YEDEK PARÇA SHOP</h1><p>Zemin yıkama makineleriniz için güvenilir yedek parçaları keşfedin.</p><div className="shopSearch"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Ürün adı veya koduyla ara"/><button>ARA</button></div></div><div className="heroPart"><span/></div></section>
  <div className="shopBar"><b>{shown.length} ürün listeleniyor</b><button className="shopCartButton" type="button" onClick={()=>setCartOpen(true)} aria-haspopup="dialog">Sepetim <span>{cartCount}</span></button></div>
  <section className="shopBody"><main><div className="categoryChips">{categories.map(x=><button className={category===x?'active':''} onClick={()=>setCategory(x)} key={x}>{x}</button>)}</div><div className="productGrid">{shown.map(p=><ProductCard key={p.id} p={p} add={addAndOpen}/>)}</div></main></section>
  {cartOpen&&<div className="cartDrawerBackdrop" onClick={()=>setCartOpen(false)}><aside className="cartDrawer" onClick={e=>e.stopPropagation()}><div className="cartHead"><h2>Sepetim ({cartCount})</h2><button type="button" onClick={()=>setCartOpen(false)} aria-label="Sepeti kapat">×</button></div>{cartProducts.length?cartProducts.map(({line,p})=><div className="miniCart drawerLine" key={line.id}><img className="partThumb" src={partImageSrc(p!)} alt=""/><div><b>{p!.name}</b><span>{money(p!.price)}</span><div className="drawerQty"><button onClick={()=>updateCart(line.qty>1?cart.map(x=>x.id===line.id?{...x,qty:x.qty-1}:x):cart.filter(x=>x.id!==line.id))}>−</button><span>{line.qty}</span><button onClick={()=>updateCart(cart.map(x=>x.id===line.id?{...x,qty:x.qty+1}:x))}>＋</button><button className="drawerRemove" onClick={()=>updateCart(cart.filter(x=>x.id!==line.id))}>Sil</button></div></div></div>):<p className="emptyCart">Sepetiniz henüz boş.</p>}<div className="cartTotal"><span>Ara toplam</span><b>{money(total)}</b></div>{cartProducts.length>0&&<><a className="shopPrimary whatsappOrder" href="/odeme">WHATSAPP’TAN SİPARİŞ VER</a><a className="drawerCartLink" href="/sepet">SEPET SAYFASINI AÇ</a></>}</aside></div>}
 </div>
}

function ProductCard({p,add}:{p:Product;add:(id:number)=>void}){return <article className="shopCard"><a href={`/yedek-parca/urun/${p.slug}`} className="partImageLink"><img src={partImageSrc(p)} alt={`${p.name} zemin yıkama makinesi yedek parçası`}/></a><small>{p.category}</small><h2><a href={`/yedek-parca/urun/${p.slug}`}>{p.name}</a></h2><p>Uyumlu: {p.compatibility}</p><span className={p.stock>0?'stock in':'stock out'}>{p.stock>0?'Stokta':'Tükendi'}</span><strong>{money(p.price)}</strong><button disabled={!p.stock} onClick={()=>add(p.id)}>🛒 SEPETE EKLE</button></article>}

function ProductDetail({product:p,add,cartCount}:{product:Product;add:(id:number)=>void;cartCount:number}){return <section className="productDetail"><div className="productPartImage"><img src={partImageSrc(p)} alt={`${p.name} ürün görseli`}/></div><article><small>{p.category} · {p.sku}</small><h1>{p.name}</h1><p>{p.description}</p><dl><div><dt>Uyumluluk</dt><dd>{p.compatibility}</dd></div><div><dt>Stok</dt><dd>{p.stock} adet</dd></div></dl><strong>{money(p.price)}</strong><button className="shopPrimary" onClick={()=>add(p.id)}>SEPETE EKLE</button><a href="/sepet">Sepete git ({cartCount}) →</a><em>Kesin uyumluluk sipariş öncesinde makine modeli üzerinden doğrulanmalıdır.</em></article></section>}

function CartCheckout({checkout,products,cart,orders,updateCart,updateOrders}:{checkout:boolean;products:Product[];cart:CartLine[];orders:Order[];updateCart:(v:CartLine[])=>void;updateOrders:(v:Order[])=>void}){
 const lines=cart.map(x=>({line:x,p:products.find(p=>p.id===x.id)})).filter(x=>x.p);const total=lines.reduce((s,x)=>s+x.p!.price*x.line.qty,0);const [done,setDone]=useState('');
 const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);const id=`ZY-${Date.now().toString().slice(-7)}`;const customer=String(f.get('customer'));const contact=String(f.get('contact'));const address=String(f.get('address'));const message=['Merhaba, zeminyikama.com Shop üzerinden sipariş vermek istiyorum.','',`Sipariş No: ${id}`,`Ad / Firma: ${customer}`,`İletişim: ${contact}`,`Teslimat Adresi: ${address}`,'','Ürünler:',...lines.map(({line,p})=>`• ${p!.name} (${p!.sku}) — ${line.qty} adet — ${money(p!.price*line.qty)}`),'',`Toplam: ${money(total)}`,'','Ürün uyumluluğunu ve teslimat koşullarını teyit eder misiniz?'].join('\n');updateOrders([{id,customer,contact,address,total,status:'WhatsApp siparişi',createdAt:new Date().toISOString()},...orders]);window.open(`https://wa.me/905375223946?text=${encodeURIComponent(message)}`,'_blank','noopener,noreferrer');updateCart([]);setDone(id)};
if(done)return <section className="orderDone"><b>✓</b><h1>Siparişiniz oluşturuldu.</h1><p>Sipariş numaranız: <strong>{done}</strong></p><a href="/yedek-parca">YEDEK PARÇAYA DÖN</a></section>;
 return <section className="cartPage"><div><small>{checkout?'TESLİMAT VE WHATSAPP SİPARİŞİ':'ALIŞVERİŞ SEPETİ'}</small><h1>{checkout?'Sipariş bilgilerinizi girin':'Sepetiniz'}</h1>{!checkout?lines.map(({line,p})=><article className="cartRow" key={line.id}><img className="partThumb" src={partImageSrc(p!)} alt=""/><div><h2>{p!.name}</h2><p>{p!.sku}</p></div><input type="number" min="1" value={line.qty} onChange={e=>updateCart(cart.map(x=>x.id===line.id?{...x,qty:Number(e.target.value)}:x))}/><strong>{money(p!.price*line.qty)}</strong><button onClick={()=>updateCart(cart.filter(x=>x.id!==line.id))}>×</button></article>):<form className="checkoutForm" onSubmit={submit}><label>Ad Soyad / Firma<input name="customer" required/></label><label>Telefon<input name="contact" inputMode="tel" required/></label><label className="wide">Teslimat adresi<textarea name="address" rows={4} required/></label><p className="wide whatsappInfo">Sipariş özetiniz WhatsApp’ta hazır mesaj olarak açılır. Göndermeden önce içeriği kontrol edebilirsiniz.</p><button className="shopPrimary whatsappOrder" type="submit">WHATSAPP’TAN SİPARİŞ VER</button></form>}</div><aside><h2>Sipariş Özeti</h2>{lines.map(x=><p key={x.line.id}><span>{x.p!.name} × {x.line.qty}</span><b>{money(x.p!.price*x.line.qty)}</b></p>)}<div><span>Toplam</span><strong>{money(total)}</strong></div>{!checkout&&<a className="shopPrimary whatsappOrder" href="/odeme">WHATSAPP’TAN SİPARİŞ VER</a>}</aside></section>
}

function MachineManager(){
 const empty:AdminMachine={slug:'',name:'',kind:'Binicili',fit:'',area:'',image:'',description:''};
 const [state,setState]=useState<MachineAdminState>({hidden:[],custom:[]});
 const [draft,setDraft]=useState<AdminMachine>(empty);
 const [adding,setAdding]=useState(false);
 const [editingSlug,setEditingSlug]=useState('');
 const [categories,setCategories]=useState<string[]>(['Binicili','İtmeli','Akülü','Süpürücü']);
 const [newCategory,setNewCategory]=useState('');
 const [imageError,setImageError]=useState('');
 useEffect(()=>{const stored=load<MachineAdminState>(machineAdminKey,{hidden:[],custom:[]});setState({hidden:Array.isArray(stored.hidden)?stored.hidden:[],custom:Array.isArray(stored.custom)?stored.custom:[]});setCategories(load('zy-machine-categories',['Binicili','İtmeli','Akülü','Süpürücü']))},[]);
 const persist=(next:MachineAdminState)=>{setState(next);save(machineAdminKey,next);window.dispatchEvent(new Event('zy-machines-updated'))};
 const visible=[...baseMachines.filter(x=>!state.hidden.includes(x.slug)).map(x=>state.custom.find(c=>c.slug===x.slug)||x),...state.custom.filter(x=>!baseMachines.some(b=>b.slug===x.slug))];
 const remove=(slug:string)=>{const isBase=baseMachines.some(x=>x.slug===slug);persist({hidden:isBase?[...new Set([...state.hidden,slug])]:state.hidden,custom:state.custom.filter(x=>x.slug!==slug)})};
 const restore=(slug:string)=>persist({...state,hidden:state.hidden.filter(x=>x!==slug)});
 const chooseImage=(file?:File)=>{if(!file)return;if(file.size>20*1024*1024){setImageError('Görsel 20 MB’den küçük olmalıdır.');return}setImageError('Görsel optimize ediliyor…');const url=URL.createObjectURL(file);const img=new Image();img.onload=()=>{const max=1600;const scale=Math.min(1,max/Math.max(img.width,img.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.width*scale));canvas.height=Math.max(1,Math.round(img.height*scale));const ctx=canvas.getContext('2d');if(!ctx){setImageError('Görsel işlenemedi.');URL.revokeObjectURL(url);return}ctx.drawImage(img,0,0,canvas.width,canvas.height);setDraft(x=>({...x,image:canvas.toDataURL('image/webp',.82)}));setImageError('');URL.revokeObjectURL(url)};img.onerror=()=>{setImageError('Görsel okunamadı. PNG, JPG veya WEBP deneyin.');URL.revokeObjectURL(url)};img.src=url};
 const openEditor=(item?:AdminMachine)=>{setDraft(item?{...item}:empty);setEditingSlug(item?.slug||'');setAdding(true);setImageError('')};
 const submit=(e:FormEvent)=>{e.preventDefault();const slug=editingSlug||draft.slug||draft.name.toLocaleLowerCase('tr-TR').replace(/[^a-z0-9çğıöşü]+/g,'-').replace(/^-|-$/g,'');persist({...state,hidden:state.hidden.filter(x=>x!==slug),custom:[...state.custom.filter(x=>x.slug!==slug),{...draft,slug}]});setDraft(empty);setEditingSlug('');setAdding(false)};
 const addCategory=()=>{const value=newCategory.trim();if(!value||categories.includes(value))return;const next=[...categories,value];setCategories(next);save('zy-machine-categories',next);setNewCategory('')};
 const deleteCategory=(value:string)=>{if(visible.some(x=>x.kind===value)){alert('Bu kategoride makine bulunuyor. Önce makinelerin kategorisini değiştirin.');return}const next=categories.filter(x=>x!==value);setCategories(next);save('zy-machine-categories',next)};
 return <section className="machineManager"><div className="machineManagerHead"><div><h2>Makine Modelleri</h2><p>Bir modele dokunarak ayrıntılarını açabilir, düzenleyebilir veya kaldırabilirsiniz.</p></div><button onClick={()=>openEditor()}>＋ YENİ MAKİNE EKLE</button></div><section className="machineCategoryAdmin"><div><input value={newCategory} onChange={e=>setNewCategory(e.target.value)} placeholder="Yeni kategori adı"/><button type="button" onClick={addCategory}>KATEGORİ EKLE</button></div><nav>{categories.map(x=><span key={x}>{x}<button type="button" aria-label={`${x} kategorisini sil`} onClick={()=>deleteCategory(x)}>×</button></span>)}</nav></section>{adding&&<form className="machineAdminForm" onSubmit={submit}><h3 className="wide">{editingSlug?'Makineyi Düzenle':'Yeni Makine Ekle'}</h3><label className="machineImageUpload"><span>Vitrin görseli</span>{draft.image?<img src={draft.image} alt="Seçilen makine görseli"/>:<div>GÖRSEL SEÇİLMEDİ</div>}<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>chooseImage(e.target.files?.[0])}/><b>Bilgisayardan görsel seç</b><small>PNG, JPG veya WEBP · En fazla 20 MB</small>{imageError&&<em>{imageError}</em>}</label><label>Model adı<input required value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>Kategori<select value={draft.kind} onChange={e=>setDraft({...draft,kind:e.target.value})}>{categories.map(x=><option key={x}>{x}</option>)}</select></label><label>Kısa açıklama<input required value={draft.fit} onChange={e=>setDraft({...draft,fit:e.target.value})}/></label><label>Kullanım alanı<input required value={draft.area} onChange={e=>setDraft({...draft,area:e.target.value})}/></label><label className="wide">Ürün açıklaması<textarea rows={5} value={draft.description||''} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><div className="wide editActions"><button type="button" onClick={()=>{setAdding(false);setEditingSlug('')}}>İptal</button><button type="submit">Makineyi Kaydet</button></div></form>}<div className="machineAdminGrid">{visible.map(x=><article key={x.slug} className="machineAdminItem" onClick={()=>openEditor(x)}>{x.image?<img src={x.image} alt=""/>:<div className="machinePlaceholder">GÖRSEL</div>}<div><small>{x.kind}</small><h3>{x.name}</h3><p>{x.fit}</p><b>AYRINTILARI AÇ / DÜZENLE →</b></div><button onClick={e=>{e.stopPropagation();if(confirm(`${x.name} kaldırılsın mı?`))remove(x.slug)}}>KALDIR</button></article>)}</div>{state.hidden.length>0&&<div className="hiddenMachines"><h3>Kaldırılan modeller</h3>{state.hidden.map(slug=><button key={slug} onClick={()=>restore(slug)}>↻ {baseMachines.find(x=>x.slug===slug)?.name||slug} modelini geri getir</button>)}</div>}</section>
}

function AdminGate({children}:{children:React.ReactNode}){
 void children;
 return <main className="adminLogin"><div className="adminLoginLogo" aria-label="Zeminyikama.com"/><small>DEMO SÜRÜMÜ</small><h1>Yönetim Alanı Kapalı</h1><p>Güvenlik nedeniyle herkese açık demo yayınında yönetim paneli devre dışıdır.</p><a href="/yedek-parca">← Yedek parçaya dön</a></main>
}

function Admin({products,orders,updateProducts,updateOrders}:{products:Product[];orders:Order[];updateProducts:(v:Product[])=>void;updateOrders:(v:Order[])=>void}){
 const empty:Product={id:0,slug:'',name:'',sku:'',category:'Fırçalar',compatibility:'',price:0,stock:0,image:0,active:true,description:''};
 const [draft,setDraft]=useState<Product>(empty);const [editing,setEditing]=useState(false);const [tab,setTab]=useState('Ürünler');const [newCategory,setNewCategory]=useState('');const [customCategories,setCustomCategories]=useState<string[]>([]);const [imageError,setImageError]=useState('');
 const [settings,setSettings]=useState({storeName:'Zemin Yıkama Yedek Parça Shop',phone:'',whatsapp:'',email:'',shipping:'150'});const [settingsSaved,setSettingsSaved]=useState(false);
 const [brands,setBrands]=useState<string[]>([]);const [newBrand,setNewBrand]=useState('');const [coupons,setCoupons]=useState<{code:string;discount:number;active:boolean}[]>([]);const [newCoupon,setNewCoupon]=useState('');
 useEffect(()=>{setSettings(load('zy-shop-settings',settings));setBrands(load('zy-shop-brands',['Nilfisk','Tennant','Hako']));setCoupons(load('zy-shop-coupons',[]));setCustomCategories(load('zy-shop-categories',[]))},[]);
 const active=products.filter(x=>x.active).length;const low=products.filter(x=>x.stock<10).length;const categories=Array.from(new Set([...products.map(x=>x.category),...customCategories])).sort();
 const chooseImage=(file?:File)=>{if(!file)return;if(file.size>20*1024*1024){setImageError('Görsel 20 MB’den küçük olmalıdır.');return}setImageError('Görsel optimize ediliyor…');const url=URL.createObjectURL(file);const img=new Image();img.onload=()=>{const max=1600;const scale=Math.min(1,max/Math.max(img.width,img.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.width*scale));canvas.height=Math.max(1,Math.round(img.height*scale));const ctx=canvas.getContext('2d');if(!ctx){setImageError('Görsel işlenemedi.');URL.revokeObjectURL(url);return}ctx.drawImage(img,0,0,canvas.width,canvas.height);const optimized=canvas.toDataURL('image/webp',.84);setDraft(x=>({...x,imageUrl:optimized}));setImageError('');URL.revokeObjectURL(url)};img.onerror=()=>{setImageError('Bu görsel okunamadı. PNG, JPG veya WEBP deneyin.');URL.revokeObjectURL(url)};img.src=url};
 const submit=(e:FormEvent)=>{e.preventDefault();const item={...draft,id:draft.id||Date.now(),slug:draft.slug||draft.name.toLocaleLowerCase('tr-TR').replace(/[^a-z0-9çğıöşü]+/g,'-').replace(/^-|-$/g,'')};updateProducts(draft.id?products.map(x=>x.id===draft.id?item:x):[item,...products]);setDraft(empty);setEditing(false)};
 const nav=['Kontrol Paneli','Siparişler','Ürünler','Kategoriler','Markalar','Stok','Müşteriler','Raporlar','Kuponlar','Ayarlar'];
 const editor=editing&&<form className="adminEdit" onSubmit={submit}><h2>{draft.id?'Ürün Düzenle':'Yeni Ürün Ekle'}</h2><label className="imageUpload"><span>Ürün görseli</span><div className={partClass(draft.image)} style={partStyle(draft)}/><input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>chooseImage(e.target.files?.[0])}/><b>Bilgisayardan görsel seç</b><small>PNG, JPG veya WEBP · En fazla 20 MB · Otomatik optimize edilir</small>{imageError&&<em>{imageError}</em>}</label>{draft.imageUrl&&<button className="removeImage" type="button" onClick={()=>setDraft({...draft,imageUrl:undefined})}>Yüklenen görseli kaldır</button>}<label>Ürün adı<input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})} required/></label><label>SKU<input value={draft.sku} onChange={e=>setDraft({...draft,sku:e.target.value})} required/></label><label>Kategori<select value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})}>{categories.map(x=><option key={x}>{x}</option>)}</select></label><div><label>Stok<input type="number" min="0" value={draft.stock} onChange={e=>setDraft({...draft,stock:Number(e.target.value)})}/></label><label>Fiyat<input type="number" min="0" value={draft.price} onChange={e=>setDraft({...draft,price:Number(e.target.value)})}/></label></div><label>Uyumluluk<input value={draft.compatibility} onChange={e=>setDraft({...draft,compatibility:e.target.value})}/></label><label>Hazır görsel kullan<select value={draft.image} onChange={e=>setDraft({...draft,image:Number(e.target.value),imageUrl:undefined})}>{defaults.map((x,i)=><option value={i} key={i}>Yedek parça görseli {i+1}</option>)}</select></label><label>Açıklama<textarea rows={4} value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><label className="adminCheck"><input type="checkbox" checked={draft.active} onChange={e=>setDraft({...draft,active:e.target.checked})}/> Ürün yayında</label><div className="editActions"><button type="button" onClick={()=>setEditing(false)}>İptal</button><button type="submit">Kaydet</button></div></form>;
 return <div className="adminApp"><aside className="adminSide"><div className="adminBrand">zemin<span>yıkama.com</span></div>{nav.map((x,i)=><button className={tab===x?'active':''} onClick={()=>{setTab(x);setEditing(false)}} key={x}>{['⌂','▣','▤','◇','▦','⚙'][i]} {x}</button>)}<a href="/shop">← Shop’a dön</a></aside><main className="adminMain"><header><div><small>KONTROL PANELİ / {tab.toUpperCase()}</small><h1>{tab==='Kontrol Paneli'?'GENEL DURUM':tab.toUpperCase()}</h1></div>{tab==='Ürünler'&&<button onClick={()=>{setDraft(empty);setEditing(true)}}>＋ YENİ ÜRÜN EKLE</button>}</header><section className="adminStats"><article><span>Toplam Ürün</span><b>{products.length}</b></article><article><span>Düşük Stoklu</span><b>{low}</b></article><article><span>Yeni Sipariş</span><b>{orders.filter(x=>x.status==='Yeni sipariş').length}</b></article><article><span>Aktif Ürün</span><b>{active}</b></article></section>
 {tab==='Kontrol Paneli'&&<section className="adminPanels"><article><h2>Mağaza Özeti</h2><p>Shop’ta {active} aktif ürün ve {categories.length} kategori bulunuyor.</p><button onClick={()=>setTab('Ürünler')}>Ürünleri yönet</button></article><article><h2>Stok Uyarısı</h2><p>{low} ürünün stoğu 10 adedin altında.</p><button onClick={()=>setTab('Stok')}>Stokları kontrol et</button></article><article><h2>Siparişler</h2><p>{orders.length} sipariş kaydı bulunuyor.</p><button onClick={()=>setTab('Siparişler')}>Siparişleri aç</button></article></section>}
 {tab==='Ürünler'&&<section className="adminWorkspace"><div className="adminTable"><div className="tableTitle"><h2>Ürünler</h2><span>{products.length} kayıt</span></div>{products.map(p=><article key={p.id}><div className={partClass(p.image)} style={partStyle(p)}/><div><b>{p.name}</b><small>{p.sku}</small></div><span>{p.category}</span><strong className={p.stock<10?'low':''}>{p.stock}</strong><b>{money(p.price)}</b><em className={p.active?'on':'off'}>{p.active?'Aktif':'Pasif'}</em><button aria-label="Düzenle" onClick={()=>{setDraft(p);setEditing(true)}}>✎</button><button aria-label="Sil" onClick={()=>{if(confirm(`${p.name} silinsin mi?`))updateProducts(products.filter(x=>x.id!==p.id))}}>×</button></article>)}</div>{editor}</section>}
 {tab==='Siparişler'&&<section className="adminList"><h2>Siparişler</h2>{orders.length?orders.map(o=><article key={o.id}><div><b>Sipariş: {o.id}</b><span><strong>{o.customer}</strong> · {o.contact}</span><small>{o.address}</small><small>{new Date(o.createdAt).toLocaleString('tr-TR')}</small></div><strong>{money(o.total)}</strong><select value={o.status} onChange={e=>updateOrders(orders.map(x=>x.id===o.id?{...x,status:e.target.value}:x))}><option>Yeni sipariş</option><option>Hazırlanıyor</option><option>Kargoya verildi</option><option>Tamamlandı</option><option>İptal</option></select></article>):<p className="adminEmpty">Henüz sipariş bulunmuyor. Shop üzerinden oluşturulan siparişler burada görünecek.</p>}</section>}
 {tab==='Kategoriler'&&<section className="adminList"><div className="tableTitle"><h2>Kategoriler</h2><form onSubmit={e=>{e.preventDefault();const name=newCategory.trim();if(name&&!categories.includes(name)){const next=[...customCategories,name];setCustomCategories(next);save('zy-shop-categories',next)}setNewCategory('')}}><input aria-label="Yeni kategori" value={newCategory} onChange={e=>setNewCategory(e.target.value)} placeholder="Yeni kategori adı" required/><button>EKLE</button></form></div>{categories.map(c=><article key={c}><div><b>{c}</b><span>{products.filter(p=>p.category===c).length} ürün</span></div><button onClick={()=>{setDraft({...empty,category:c});setEditing(true);setTab('Ürünler')}}>Bu kategoriye ürün ekle</button><button disabled={products.some(p=>p.category===c)} title="İçinde ürün bulunan kategori silinemez" onClick={()=>{const next=customCategories.filter(x=>x!==c);setCustomCategories(next);save('zy-shop-categories',next)}}>Sil</button></article>)}</section>}
 {tab==='Stok'&&<section className="adminList"><h2>Hızlı Stok Yönetimi</h2>{products.map(p=><article key={p.id}><div><b>{p.name}</b><span>{p.sku}</span></div><strong className={p.stock<10?'low':''}>{p.stock} adet</strong><div className="stockButtons"><button onClick={()=>updateProducts(products.map(x=>x.id===p.id?{...x,stock:Math.max(0,x.stock-1)}:x))}>−</button><button onClick={()=>updateProducts(products.map(x=>x.id===p.id?{...x,stock:x.stock+1}:x))}>＋</button></div></article>)}</section>}
 {tab==='Markalar'&&<section className="adminList"><div className="tableTitle"><h2>Markalar</h2><form onSubmit={e=>{e.preventDefault();if(newBrand&&!brands.includes(newBrand)){const next=[...brands,newBrand];setBrands(next);save('zy-shop-brands',next)}setNewBrand('')}}><input aria-label="Yeni marka" value={newBrand} onChange={e=>setNewBrand(e.target.value)} placeholder="Marka adı"/><button>EKLE</button></form></div>{brands.map(b=><article key={b}><div><b>{b}</b><span>Uyumluluk ve filtrelemede kullanılabilir</span></div><button onClick={()=>{const next=brands.filter(x=>x!==b);setBrands(next);save('zy-shop-brands',next)}}>Sil</button></article>)}</section>}
 {tab==='Müşteriler'&&<section className="adminList"><h2>Müşteriler</h2>{orders.length?Array.from(new Map(orders.map(o=>[o.contact,o])).values()).map(o=><article key={o.contact}><div><b>{o.customer}</b><span>{o.contact}</span><small>{o.address}</small></div><strong>{orders.filter(x=>x.contact===o.contact).length} sipariş</strong></article>):<p className="adminEmpty">Sipariş veren müşteriler otomatik olarak burada listelenecek.</p>}</section>}
 {tab==='Raporlar'&&<section className="adminPanels"><article><h2>Toplam Satış</h2><p>Tamamlanan ve açık siparişlerin toplam değeri.</p><b>{money(orders.reduce((s,o)=>s+o.total,0))}</b></article><article><h2>Ortalama Sepet</h2><p>Sipariş başına ortalama tutar.</p><b>{money(orders.length?orders.reduce((s,o)=>s+o.total,0)/orders.length:0)}</b></article><article><h2>Stok Değeri</h2><p>Mevcut ürün stoklarının tahmini satış değeri.</p><b>{money(products.reduce((s,p)=>s+p.price*p.stock,0))}</b></article></section>}
 {tab==='Kuponlar'&&<section className="adminList"><div className="tableTitle"><h2>İndirim Kuponları</h2><form onSubmit={e=>{e.preventDefault();if(newCoupon){const next=[...coupons,{code:newCoupon.toUpperCase(),discount:10,active:true}];setCoupons(next);save('zy-shop-coupons',next)}setNewCoupon('')}}><input aria-label="Yeni kupon" value={newCoupon} onChange={e=>setNewCoupon(e.target.value)} placeholder="KUPON KODU"/><button>OLUŞTUR</button></form></div>{coupons.length?coupons.map(c=><article key={c.code}><div><b>{c.code}</b><span>%{c.discount} indirim</span></div><button onClick={()=>{const next=coupons.map(x=>x.code===c.code?{...x,active:!x.active}:x);setCoupons(next);save('zy-shop-coupons',next)}}>{c.active?'Pasife al':'Aktifleştir'}</button><button onClick={()=>{const next=coupons.filter(x=>x.code!==c.code);setCoupons(next);save('zy-shop-coupons',next)}}>Sil</button></article>):<p className="adminEmpty">Henüz kupon oluşturulmadı.</p>}</section>}
 {tab==='Ayarlar'&&<form className="adminSettings" onSubmit={e=>{e.preventDefault();save('zy-shop-settings',settings);setSettingsSaved(true);setTimeout(()=>setSettingsSaved(false),2500)}}><h2>Shop Ayarları</h2><label>Mağaza adı<input value={settings.storeName} onChange={e=>setSettings({...settings,storeName:e.target.value})}/></label><label>Telefon<input value={settings.phone} onChange={e=>setSettings({...settings,phone:e.target.value})} placeholder="05xx xxx xx xx"/></label><label>WhatsApp<input value={settings.whatsapp} onChange={e=>setSettings({...settings,whatsapp:e.target.value})} placeholder="905xx..."/></label><label>E-posta<input value={settings.email} onChange={e=>setSettings({...settings,email:e.target.value})}/></label><label>Ücretsiz kargo limiti<input type="number" value={settings.shipping} onChange={e=>setSettings({...settings,shipping:e.target.value})}/></label><button className="shopPrimary">AYARLARI KAYDET</button>{settingsSaved&&<b className="saveNotice">✓ Ayarlar kaydedildi</b>}</form>}
 </main></div>
}
