'use client';
import Link from 'next/link';
import {FormEvent,useMemo,useState} from 'react';

declare global{interface Window{dataLayer?:Record<string,unknown>[]}}
const event=(name:string,data:Record<string,unknown>={})=>{if(typeof window!=='undefined'){window.dataLayer=window.dataLayer||[];window.dataLayer.push({event:name,...data})}};
const machines=[
 {slug:'kompakt-iticili',name:'Kompakt İticili',kind:'İtmeli',fit:'Dar geçişler ve günlük bakım temizliği',area:'Küçük ve orta ölçekli alanlar'},
 {slug:'profesyonel-iticili',name:'Profesyonel İticili',kind:'Akülü',fit:'Depo koridorları ve düzenli saha bakımı',area:'Orta ölçekli alanlar'},
 {slug:'binicili-platform',name:'Binicili Platform',kind:'Binicili',fit:'Geniş yüzeylerde planlı temizlik akışı',area:'Geniş endüstriyel alanlar'},
 {slug:'endustriyel-supurucu',name:'Endüstriyel Süpürücü',kind:'Süpürücü',fit:'Toz ve katı atık yoğun sahalar',area:'Depo, fabrika ve dış alanlar'},
 {slug:'agir-hizmet-supurucu',name:'Ağır Hizmet Süpürücü',kind:'Süpürücü',fit:'Yoğun toz ve atık bulunan çalışma sahaları',area:'Fabrika ve lojistik alanları'},
 {slug:'tek-diskli-profesyonel',name:'Tek Diskli Profesyonel',kind:'Tek Diskli',fit:'Detaylı bakım ve yüzey uygulamaları',area:'Küçük ve kontrollü alanlar'},
 {slug:'orta-sinif-binicili',name:'Orta Sınıf Binicili',kind:'Binicili',fit:'Orta ve geniş alanlarda çevik sürüş',area:'Ticari ve endüstriyel alanlar'},
 {slug:'kombine-supurucu-yikayici',name:'Kombine Süpürücü Yıkayıcı',kind:'Kombine',fit:'Süpürme ve yıkama ihtiyacını birleştiren sahalar',area:'Büyük depo ve üretim alanları'},
];
const sectorData=[['fabrika','Fabrikalar'],['avm','AVM’ler'],['depo','Depolar'],['otopark','Otoparklar'],['hastane','Hastaneler'],['otel','Oteller'],['market','Marketler'],['okul','Okullar'],['belediye','Belediyeler'],['lojistik','Lojistik Merkezleri']];
const posts=[
 ['zemin-tipine-gore-makine-secimi','Zemin Tipine Göre Makine Seçimi','Kaplama, kir türü, geçiş genişliği ve çalışma düzenini tek kararda birleştirin.'],
 ['kiralama-mi-satin-alma-mi','Kiralama mı, Satın Alma mı?','Kullanım sıklığı ve bakım sorumluluğuna göre iki modeli değerlendirin.'],
 ['temizlik-makinesi-bakim-plani','Sürdürülebilir Bakım Planı','Günlük kontrolden servis kaydına uzanan uygulanabilir bir düzen kurun.'],
 ['fabrika-zemin-temizligi-planlama','Fabrika Zemin Temizliği Nasıl Planlanır?','Üretim akışını aksatmadan vardiya, güvenli çalışma bölgesi ve kir yoğunluğuna göre uygulanabilir bir temizlik planı hazırlayın.'],
 ['depo-koridorlarinda-makine-secimi','Depo Koridorlarında Makine Seçimi','Raf araları, dönüş noktaları, kapı açıklıkları ve sevkiyat trafiğini birlikte değerlendirerek uygun makine sınıfını belirleyin.'],
 ['gunluk-makine-kontrol-listesi','Günlük Makine Kontrol Listesi','Her vardiya öncesi ve sonrasında uygulanabilecek kısa kontrollerle kullanım düzenini koruyun ve olası aksaklıkları erkenden fark edin.'],
];

function Header(){return <><div className="siteTop"><div><span>◇ Türkiye Geneli Hizmet</span><span>◉ Uzman Teknik Destek</span><span>◇ Yedek Parça Süreci</span></div><div><a href="https://wa.me/905550000000" onClick={()=>event('whatsapp_click')}>◉ WhatsApp</a><Link href="/iletisim">İletişim Talebi</Link></div></div><header className="siteHeader"><Link className="siteLogo" href="/"><b>ZEMİN YIKAMA</b><span>MAKİNELERİ</span></Link><nav><Link href="/">ANA SAYFA</Link><Link href="/makineler">MAKİNELER⌄</Link><Link href="/kiralama">HİZMETLER⌄</Link><Link href="/sektorler">SEKTÖREL ÇÖZÜMLER⌄</Link><Link href="/blog">BLOG</Link><Link href="/iletisim">İLETİŞİM</Link></nav><Link className="blueBtn" href="/teklif-al">TEKLİF AL</Link></header></>}
function Sticky(){return <div className="siteSticky"><a href="tel:+905550000000" onClick={()=>event('click_to_call')}>☎<span><b>HEMEN ARA</b><small>TELEFON TALEBİ</small></span></a><a href="https://wa.me/905550000000" onClick={()=>event('whatsapp_click')}>◉<span><b>WHATSAPP</b><small>HIZLI BİLGİ AL</small></span></a><Link href="/teklif-al" onClick={()=>event('cta_click',{place:'sticky'})}>▣<span><b>TEKLİF AL</b><small>ÜCRETSİZ TALEP</small></span></Link></div>}
function Footer(){return <footer className="siteFooter"><div><Link className="siteLogo light" href="/"><b>ZEMİN YIKAMA</b><span>MAKİNELERİ</span></Link><p>Profesyonel zemin temizliği için makine seçimi, kiralama, servis ve yedek parça süreçleri.</p></div><div><b>MAKİNELER</b><Link href="/makineler/binicili">Binicili</Link><Link href="/makineler/iticili">İtmeli</Link><Link href="/makineler/supuruculer">Süpürücüler</Link></div><div><b>HİZMETLER</b><Link href="/kiralama">Kiralama</Link><Link href="/servis">Servis</Link><Link href="/yedek-parca">Yedek Parça</Link><Link href="/ikinci-el">İkinci El</Link></div><div><b>HIZLI ERİŞİM</b><Link href="/makine-secici">Makine Seçici</Link><Link href="/karsilastir">Karşılaştırma</Link><Link href="/blog">Bilgi Merkezi</Link><Link href="/teklif-al">Teklif Al</Link></div><small className="footerNote">© Zemin Yıkama Makineleri · Model özellikleri, fiyat ve ticari koşullar teklif aşamasında doğrulanır.</small></footer>}
function Shell({children}:{children:React.ReactNode}){return <main className="site"><Header/>{children}<Footer/><Sticky/></main>}
function Breadcrumb({items}:{items:string[]}){return <nav className="breadcrumb"><Link href="/">Ana Sayfa</Link>{items.map(x=><span key={x}>› {x}</span>)}</nav>}
function Hero({eyebrow,title,text}:{eyebrow:string,title:string,text:string}){return <section className="subHero"><div className="subHeroShade"/><div className="subHeroInner"><Breadcrumb items={[title]}/><strong>{eyebrow}</strong><h1>{title}</h1><p>{text}</p><Link className="blueBtn" href="/teklif-al">ÜCRETSİZ TEKLİF AL</Link></div></section>}
function Benefits(){return <section className="darkBenefits">{[['♙','Uzman Yönlendirme'],['◈','Geniş Çözüm Yelpazesi'],['✹','Teknik Servis Desteği'],['⚙','Yedek Parça Süreci'],['◉','Satış Sonrası Destek']].map(x=><div key={x[1]}><i>{x[0]}</i><span><b>{x[1]}</b><small>Talebinize göre planlı süreç</small></span></div>)}</section>}
function BottomCTA(){return <section className="bottomCta"><div><small>DOĞRU MAKİNEYİ BİRLİKTE BELİRLEYELİM</small><h2>Sahanız için uygun çözümü bulun.</h2><p>Alan, zemin ve çalışma düzeninizi paylaşın; doğrulanmış bilgilerle ilerleyin.</p></div><Link className="greenBtn" href="/teklif-al">HEMEN TEKLİF AL →</Link></section>}
function MachineGraphic({tone=0}:{tone?:number}){return <div className={`cssMachine tone${tone}`}><i/><em/><b/><span/></div>}

function Catalog({category}:{category?:string}){const title=category==='binicili'?'Binicili Zemin Yıkama Makineleri':category==='iticili'?'İtmeli Zemin Yıkama Makineleri':category==='supuruculer'?'Endüstriyel Süpürücüler':'Zemin Yıkama Makineleri';const shown=machines.filter(m=>!category||(category==='binicili'?m.kind==='Binicili':category==='iticili'?['İtmeli','Akülü'].includes(m.kind):m.kind==='Süpürücü'));return <Shell><Hero eyebrow="PROFESYONEL MAKİNE ÇÖZÜMLERİ" title={title} text="Sahanızın yapısına göre makine sınıflarını inceleyin. Teknik değerler ve ticari koşullar talep sırasında doğrulanır."/><Benefits/><section className="pageSection"><div className="sectionTitle"><div><small>MAKİNE KATEGORİLERİ</small><h2>İhtiyacınıza göre filtreleyin</h2></div><div className="pills"><Link href="/makineler">Tümü</Link><Link href="/makineler/binicili">Binicili</Link><Link href="/makineler/iticili">İtmeli</Link><Link href="/makineler/supuruculer">Süpürücü</Link></div></div><div className="machineGrid">{shown.map((m,i)=><article className="machineCard" key={m.slug}><div className="cardVisual"><MachineGraphic tone={i}/><span>{m.kind}</span></div><small>{m.kind.toUpperCase()}</small><h2>{m.name}</h2><p>{m.fit}</p><dl><div><dt>Alan yaklaşımı</dt><dd>{m.area}</dd></div><div><dt>Bilgi durumu</dt><dd>Teklif sırasında teyit edilir</dd></div></dl><div className="cardButtons"><Link className="blueBtn" href={`/urun/${m.slug}`}>İNCELE</Link><Link href="/karsilastir">KARŞILAŞTIR →</Link></div></article>)}</div></section><BottomCTA/></Shell>}
function Product({slug}:{slug:string}){const m=machines.find(x=>x.slug===slug)||machines[0];return <Shell><section className="productHero"><div><Breadcrumb items={['Makineler',m.name]}/><strong>{m.kind.toUpperCase()} ZEMİN TEMİZLEME</strong><h1>{m.name}</h1><p>{m.fit}. Kesin ürün yapısı, kapasite, garanti ve fiyat bilgileri teyitli teklif kapsamında paylaşılır.</p><div className="heroActions"><Link className="blueBtn" href="/teklif-al">TEKLİF AL</Link><Link className="outlineBtn" href="/karsilastir">KARŞILAŞTIR</Link></div></div><div className="productMachine"><MachineGraphic tone={2}/></div></section><Benefits/><section className="pageSection twoColumns"><article><small>ÜRÜN YAKLAŞIMI</small><h2>Hangi sahalarda değerlendirilebilir?</h2><p>{m.area} için başlangıç seçeneği olarak değerlendirilebilir. Uygunluk; en dar geçiş, dönüş alanı, yüzey kaplaması, kir yapısı ve çalışma süresi birlikte incelenerek netleşir.</p><h3>Seçimden önce</h3><ul><li>Net temizlenecek alanı belirleyin.</li><li>Kapı ve koridor genişliklerini ölçün.</li><li>Zemin kaplamasını ve baskın kir türünü not edin.</li><li>Şarj, depolama ve günlük bakım alanını planlayın.</li></ul></article><aside><h3>Doğrulanmış bilgi politikası</h3><p>Teknik özellik, fiyat, garanti veya performans değeri uydurmuyoruz. İhtiyacınıza göre model teyidi yapıldıktan sonra bilgi paylaşıyoruz.</p><Link className="greenBtn" href="/teklif-al">BİLGİ İSTE →</Link></aside></section><BottomCTA/></Shell>}
const services:Record<string,{title:string;eyebrow:string;text:string;steps:string[]}>={
 kiralama:{title:'Zemin Yıkama Makinesi Kiralama',eyebrow:'ESNEK KULLANIM MODELİ',text:'Dönemsel veya sürekli ihtiyacınızı paylaşın; saha ve çalışma düzeninize uygun kiralama yaklaşımını birlikte netleştirelim.',steps:['Saha ve ihtiyaç kaydı','Makine sınıfının belirlenmesi','Teslim ve kullanım planı']},
 servis:{title:'Teknik Servis ve Bakım',eyebrow:'PLANLI DESTEK SÜRECİ',text:'Arıza, bakım ve kontrol taleplerini kayıtlı bir akışla değerlendirin; plansız duruş riskini azaltmaya yardımcı olun.',steps:['Talep ve makine kaydı','Kontrol ve çözüm planı','İşlem sonrası bilgilendirme']},
 'yedek-parca':{title:'Zemin Yıkama Makinesi Yedek Parça',eyebrow:'UYUMLULUK TEYİTLİ SÜREÇ',text:'Makine ve ihtiyaç duyulan parça bilgilerini iletin; uyumluluk doğrulandıktan sonra tedarik adımına geçin.',steps:['Model bilgisinin alınması','Parça uyumluluğunun kontrolü','Tedarik yönlendirmesi']},
 'ikinci-el':{title:'İkinci El Zemin Yıkama Makineleri',eyebrow:'KONTROLLÜ ALTERNATİFLER',text:'Mevcut durumu açıkça belirtilen seçenekleri inceleyin; stok ve koşulları talep sırasında doğrulayın.',steps:['İhtiyaç profilinin çıkarılması','Mevcut seçeneklerin paylaşılması','Durum ve kapsam teyidi']}
};
function Service({kind}:{kind:string}){const s=services[kind];return <Shell><Hero eyebrow={s.eyebrow} title={s.title} text={s.text}/><Benefits/><section className="pageSection serviceIntro"><div><small>SÜREÇ YAKLAŞIMI</small><h2>Sade, şeffaf ve sahaya odaklı.</h2><p>Genel vaatler yerine ihtiyacınıza göre netleşen adımlarla ilerleyin. Her teknik ve ticari detay, ilgili makine ve saha bilgisi üzerinden doğrulanır.</p></div><div className="processGrid">{s.steps.map((x,i)=><article key={x}><span>0{i+1}</span><h3>{x}</h3><p>İlgili bilgiler kaydedilir, kontrol edilir ve sonraki adım açıkça paylaşılır.</p></article>)}</div></section><section className="imageBand"><div><strong>OPERASYONU DURDURMADAN</strong><h2>Temizlik sürecinizi planlayın.</h2><p>İhtiyaç türünü ve çalışma düzenini formda belirtin.</p></div></section><BottomCTA/></Shell>}
function Sectors({slug}:{slug?:string}){const current=sectorData.find(x=>x[0]===slug);if(current)return <Shell><Hero eyebrow="SEKTÖREL TEMİZLİK ÇÖZÜMLERİ" title={`${current[1]} İçin Zemin Temizliği`} text={`${current[1]} için zemin, trafik, çalışma saati ve temizlik hedefini birlikte değerlendiren saha odaklı yaklaşım.`}/><Benefits/><section className="pageSection twoColumns"><article><small>SAHAYA GÖRE PLANLAMA</small><h2>Tek bir ölçü yetmez.</h2><p>{current[1]} için makine seçimi yalnızca metrekareye göre yapılmamalıdır. Dar geçişler, dönüş noktaları, zemin kaplaması, baskın kir türü ve temizliğe ayrılan süre birlikte ele alınır.</p><h3>Değerlendirilecek başlıklar</h3><ul><li>Zemin kaplaması ve eğim durumu</li><li>Yaya veya araç trafik yoğunluğu</li><li>Temizlik saatleri ve güvenli çalışma alanı</li><li>Depolama, şarj ve günlük bakım noktası</li></ul></article><aside><h3>Alanınızı kısaca tarif edin</h3><p>Doğrulanmamış teknik değerler vermeden uygun makine sınıfını birlikte daraltalım.</p><Link className="greenBtn" href="/teklif-al">SAHA TALEBİ OLUŞTUR →</Link></aside></section><BottomCTA/></Shell>;return <Shell><Hero eyebrow="SEKTÖREL ÇÖZÜMLER" title="Her Sektöre Özel Zemin Temizliği" text="Farklı saha koşulları için aynı makineyi önermek yerine, kullanım düzenine göre doğru başlangıç noktasını bulun."/><section className="pageSection"><div className="sectorPageGrid">{sectorData.map((s,i)=><Link href={`/sektorler/${s[0]}`} key={s[0]}><div className={`sectorImage sector${i}`}/><div><h2>{s[1]}</h2><p>Sahaya özel seçim kriterlerini inceleyin.</p><b>DETAYLARI GÖR →</b></div></Link>)}</div></section><Benefits/><BottomCTA/></Shell>}
function Blog({slug}:{slug?:string}){const p=posts.find(x=>x[0]===slug);if(p)return <Shell><article className="articlePage"><Breadcrumb items={['Blog',p[1]]}/><strong>ÖZGÜN REHBER</strong><h1>{p[1]}</h1><p className="articleLead">{p[2]}</p><div className="articleCover"/><h2>Kararı sahadan başlatın</h2><p>Makine seçiminde tek bir ölçüte güvenmek yanıltıcı olabilir. Kullanım alanının net büyüklüğü kadar geçişler, dönüş noktaları, yüzey yapısı ve temizlik için ayrılan zaman da değerlendirilmelidir.</p><h2>Toplam kullanım düzenini düşünün</h2><p>Makinenin gün içinde nasıl kullanılacağı, nerede saklanacağı, günlük kontrolleri kimin yapacağı ve servis kaydının nasıl tutulacağı seçimin sürdürülebilirliğini etkiler.</p><blockquote>Modele özel teknik bilgiler üretici belgeleri ve teklif kapsamıyla teyit edilmelidir.</blockquote><h2>Uygulanabilir kontrol listesi</h2><ol><li>Net temizlenecek alanı belirleyin.</li><li>En dar geçiş ve dönüş alanını ölçün.</li><li>Zemin ve baskın kir türünü not edin.</li><li>Temizlik zaman aralığını planlayın.</li><li>Bakım sorumluluğunu tanımlayın.</li></ol></article><BottomCTA/></Shell>;return <Shell><Hero eyebrow="BİLGİ MERKEZİ" title="Daha Bilinçli Bir Seçim İçin" text="Sıfırdan hazırlanmış, karar süreçlerini kolaylaştıran özgün rehberler ve saha notları."/><section className="pageSection blogGrid">{posts.map((p,i)=><Link href={`/blog/${p[0]}`} key={p[0]}><div className={`blogPic blog${i}`}/><small>REHBER</small><h2>{p[1]}</h2><p>{p[2]}</p><b>OKUMAYA DEVAM ET →</b></Link>)}</section><Benefits/></Shell>}
function Quote(){const [done,setDone]=useState(false);function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget).entries());const saved=JSON.parse(localStorage.getItem('zemin-yikama-teklifleri')||'[]');localStorage.setItem('zemin-yikama-teklifleri',JSON.stringify([...saved,{...data,createdAt:new Date().toISOString()}]));event('generate_lead',{form:'quote'});setDone(true)}return <Shell><Hero eyebrow="ÜCRETSİZ TALEP" title="Teklif Formu" text="İhtiyacınızı anlatın. Teknik özellik ve ticari koşullar, verilen bilgiler değerlendirildikten sonra doğrulanır."/><section className="formSection">{done?<div className="formDone"><b>Teklif talebiniz kaydedildi.</b><p>Talebiniz bu cihazda başarıyla kaydedildi. Canlı iletişim altyapısı bağlandığında aynı form doğrudan ekibe iletilebilir.</p><Link href="/">ANA SAYFAYA DÖN →</Link></div>:<form onSubmit={submit}><div className="formHeader"><small>İHTİYAÇ BİLGİLERİ</small><h2>Size uygun çözümü belirleyelim.</h2></div><div className="formGrid"><label>Adınız / Firma adınız<input required name="name"/></label><label>Telefon veya e-posta<input required name="contact" type="text"/></label><label>İletişim tercihi<select name="channel"><option>Telefon</option><option>WhatsApp</option><option>E-posta</option></select></label><label>İhtiyaç türü<select name="need"><option>Satın alma</option><option>Kiralama</option><option>Servis</option><option>Yedek parça</option><option>İkinci el</option></select></label><label>Alan ölçeği<select name="area"><option>Henüz bilmiyorum</option><option>Küçük</option><option>Orta</option><option>Geniş</option></select></label><label className="wide">Saha ve ihtiyaç açıklaması<textarea rows={5} required name="message"/></label><label className="check wide"><input type="checkbox" required name="consent"/> Talebimin değerlendirilmesini kabul ediyorum.</label></div><button className="blueBtn" type="submit">TEKLİF TALEBİNİ KAYDET →</button></form>}</section></Shell>}
function Selector(){const [area,setArea]=useState('');const [passage,setPassage]=useState('');const answer=useMemo(()=>!area||!passage?null:area==='large'&&passage!=='narrow'?machines[2]:area==='small'?machines[0]:machines[1],[area,passage]);return <Shell><Hero eyebrow="MAKİNE SEÇİCİ" title="Hangi Makine Bana Uygun?" text="İki temel soruyla uygun makine sınıfı için başlangıç önerisi alın. Son karar saha bilgileri doğrulandıktan sonra verilmelidir."/><section className="selector"><div><label><span>01</span>Alan ölçeği<select value={area} onChange={e=>setArea(e.target.value)}><option value="">Seçin</option><option value="small">Küçük</option><option value="medium">Orta</option><option value="large">Geniş</option></select></label><label><span>02</span>Dar geçişler<select value={passage} onChange={e=>setPassage(e.target.value)}><option value="">Seçin</option><option value="narrow">Yoğun</option><option value="mixed">Kısmen</option><option value="open">Saha açık</option></select></label></div><aside>{answer?<><small>BAŞLANGIÇ ÖNERİSİ</small><h2>{answer.name}</h2><p>{answer.fit}. Bu sonuç bağlayıcı teknik öneri değildir.</p><Link className="greenBtn" href="/teklif-al">UZMAN DEĞERLENDİRMESİ →</Link></>:<><small>SONUÇ ALANI</small><h2>İki seçimi tamamlayın</h2><p>Yanıtlarınıza göre uygun başlangıç sınıfı burada görünecek.</p></>}</aside></section><Benefits/></Shell>}
function Compare(){return <Shell><Hero eyebrow="MAKİNE KARŞILAŞTIRMA" title="Makine Sınıflarını Yan Yana Görün" text="Kesin model değerleri yerine karar sürecinde anlamlı olan kullanım farklarını karşılaştırın."/><section className="compare"><table><thead><tr><th>Karar başlığı</th>{machines.slice(0,3).map(m=><th key={m.slug}>{m.name}</th>)}</tr></thead><tbody><tr><th>Tür</th>{machines.slice(0,3).map(m=><td key={m.slug}>{m.kind}</td>)}</tr><tr><th>Alan yaklaşımı</th>{machines.slice(0,3).map(m=><td key={m.slug}>{m.area}</td>)}</tr><tr><th>Kullanım odağı</th>{machines.slice(0,3).map(m=><td key={m.slug}>{m.fit}</td>)}</tr><tr><th>İşlem</th>{machines.slice(0,3).map(m=><td key={m.slug}><Link href="/teklif-al">BİLGİ İSTE →</Link></td>)}</tr></tbody></table></section><BottomCTA/></Shell>}
function Contact(){return <Shell><Hero eyebrow="İLETİŞİM" title="Size Uygun Kanaldan Ulaşalım" text="Telefon veya WhatsApp tercihinizi teklif formunda belirtin. Doğrulanmış iletişim bilgileri bağlandığında doğrudan kanallar aktif edilir."/><section className="contactCards"><Link href="/teklif-al"><b>☎</b><h2>Telefon Talebi</h2><p>Aranmak istediğinizi belirtin.</p><span>TALEP BIRAK →</span></Link><Link href="/teklif-al"><b>◉</b><h2>WhatsApp Talebi</h2><p>WhatsApp dönüş tercihinizi iletin.</p><span>TALEP BIRAK →</span></Link><Link href="/teklif-al"><b>▣</b><h2>Teklif Talebi</h2><p>İhtiyacınızı form üzerinden anlatın.</p><span>FORMA GİT →</span></Link></section><Benefits/></Shell>}
function Landing({rental}:{rental:boolean}){return <Shell><section className="landing"><div><strong>{rental?'KİRALAMA ÇÖZÜMLERİ':'PROFESYONEL MAKİNE ÇÖZÜMLERİ'}</strong><h1>{rental?'Zemin Yıkama Makinesi Kiralama':'Profesyonel Zemin Yıkama Makineleri'}</h1><p>{rental?'Dönemsel veya sürekli kullanım ihtiyacınızı paylaşın; uygun kiralama yaklaşımını birlikte belirleyelim.':'Makine sınıflarını karşılaştırın, sahanıza uygun başlangıç noktasını belirleyin ve teyitli teklif isteyin.'}</p><Link className="greenBtn" href="/teklif-al">HIZLI TEKLİF İSTE →</Link></div></section><Benefits/><BottomCTA/></Shell>}
function Missing(){return <Shell><section className="missing"><b>404</b><h1>Bu sayfa bulunamadı.</h1><p>Bağlantı değişmiş veya sayfa kaldırılmış olabilir.</p><Link className="blueBtn" href="/">ANA SAYFAYA DÖN</Link></section></Shell>}

export default function SiteShell({slug=[]}:{slug?:string[]}){const p=slug.join('/');if(p==='makineler')return <Catalog/>;if(p.startsWith('makineler/'))return <Catalog category={slug[1]}/>;if(p.startsWith('urun/'))return <Product slug={slug[1]}/>;if(services[p])return <Service kind={p}/>;if(p==='sektorler')return <Sectors/>;if(p.startsWith('sektorler/'))return <Sectors slug={slug[1]}/>;if(p==='blog')return <Blog/>;if(p.startsWith('blog/'))return <Blog slug={slug[1]}/>;if(p==='teklif-al')return <Quote/>;if(p==='makine-secici')return <Selector/>;if(p==='karsilastir')return <Compare/>;if(p==='iletisim')return <Contact/>;if(p==='lp/zemin-yikama-makinesi')return <Landing rental={false}/>;if(p==='lp/kiralama')return <Landing rental/>;return <Missing/>}
