'use client';
import {FormEvent,useMemo,useState} from 'react';
import ShopSystem from './ShopSystem';

declare global{interface Window{dataLayer?:Record<string,unknown>[]}}
const event=(name:string,data:Record<string,unknown>={})=>{if(typeof window!=='undefined'){window.dataLayer=window.dataLayer||[];window.dataLayer.push({event:name,...data})}};
type Machine={slug:string;name:string;kind:string;fit:string;area:string;image?:string;gallery?:{src:string;alt:string}[];description?:string;features?:string[];specs?:[string,string][]};
const b250Gallery=[
 {src:'/b250-showcase.webp',alt:'Ecoline B250 vitrin görseli'},
 {src:'/ecoline-b250.png',alt:'Ecoline B250 binicili zemin temizleme otomatı'},
 {src:'/b250-01-front-industrial.webp',alt:'Ecoline B250 önden görünüm'},
 {src:'/b250-02-front-white.webp',alt:'Ecoline B250 beyaz fonda ön görünüm'},
 {src:'/b250-07-side.webp',alt:'Ecoline B250 yandan görünüm'},
 {src:'/b250-08-rear.webp',alt:'Ecoline B250 arka emiş sistemi'},
 {src:'/b250-09-rear-side.webp',alt:'Ecoline B250 arka yan görünüm'},
 {src:'/b250-04-parts.webp',alt:'Ecoline B250 makine parçaları'},
 {src:'/b250-11-control-panel.webp',alt:'Ecoline B250 akıllı kontrol paneli'},
 {src:'/b250-12-brushes.webp',alt:'Ecoline B250 çift fırça ve silecek sistemi'},
 {src:'/b250-03-tanks.webp',alt:'Ecoline B250 temiz ve kirli su tankları'},
 {src:'/b250-06-tanks-detail.webp',alt:'Ecoline B250 tank kapasitesi tanıtımı'},
 {src:'/b250-05-features.webp',alt:'Ecoline B250 temel özellikleri'},
 {src:'/b250-10-slope.webp',alt:'Ecoline B250 eğimli zeminde kullanım'},
 {src:'/b250-13-details.webp',alt:'Ecoline B250 ürün ayrıntıları'},
 {src:'/b250-14-introduction.webp',alt:'Ecoline B250 özellik tanıtımı'},
 {src:'/b250-15-overview.webp',alt:'Ecoline B250 genel ürün tanıtımı'},
];
const b140Gallery=[
 {src:'/b140-showcase.webp',alt:'Berker Ecoline B140 vitrin görseli'},
 {src:'/b140-main.webp',alt:'Ecoline B140 binicili zemin temizleme makinası'},
 {src:'/b140-11.webp',alt:'Ecoline B140 beyaz fonda ürün görünümü'},
 {src:'/b140-12.webp',alt:'Ecoline B140 stüdyo görünümü'},
 {src:'/b140-13.webp',alt:'Ecoline B140 ön görünüm'},
 {src:'/b140-14.webp',alt:'Ecoline B140 arka yan görünüm'},
 {src:'/b140-15.webp',alt:'Ecoline B140 yan görünüm'},
 {src:'/b140-16.webp',alt:'Ecoline B140 arka emiş sistemi'},
 {src:'/b140-01.webp',alt:'Ecoline B140 yüzde 16 tırmanma kapasitesi'},
 {src:'/b140-02.webp',alt:'Ecoline B140 çift fırça sistemi'},
 {src:'/b140-03.webp',alt:'Ecoline B140 akıllı kontrol paneli'},
 {src:'/b140-04.webp',alt:'Ecoline B140 ölçüleri ve ürün özellikleri'},
 {src:'/b140-05.webp',alt:'Ecoline B140 otomatik temizlik karşılaştırması'},
 {src:'/b140-06.webp',alt:'Ecoline B140 derin temizlik fırçaları'},
 {src:'/b140-07.webp',alt:'Ecoline B140 eğimli zeminde kullanım'},
 {src:'/b140-08.webp',alt:'Ecoline B140 vakum sileceği ve LED farları'},
 {src:'/b140-09.webp',alt:'Ecoline B140 öne çıkan özellikler'},
 {src:'/b140-10.webp',alt:'Ecoline B140 ürün ayrıntıları'},
 {src:'/b140-17.webp',alt:'Ecoline B140 iş gücü verimliliği karşılaştırması'},
];
const b60Gallery=[
 {src:'/b60-showcase.webp',alt:'Ecoline B60 vitrin görseli'},
 {src:'/b60-01.webp',alt:'Ecoline B60 beyaz fonda ürün görünümü'},
 {src:'/b60-02.webp',alt:'Ecoline B60 çift su tankı sistemi'},
 {src:'/b60-03.webp',alt:'Ecoline B60 ofis ortamında kullanım'},
 {src:'/b60-04.webp',alt:'Ecoline B60 fırça sistemi'},
 {src:'/b60-05.webp',alt:'Ecoline B60 akıllı kontrol paneli'},
 {src:'/b60-06.webp',alt:'Ecoline B60 teknik özellik görünümü'},
 {src:'/b60-07.webp',alt:'Ecoline B60 beyaz fonda yan görünüm'},
 {src:'/b60-08.webp',alt:'Ecoline B60 temel özellikleri'},
 {src:'/b60-09.webp',alt:'Ecoline B60 fabrika ortamında kullanım'},
 {src:'/b60-10.webp',alt:'Ecoline B60 kullanım alanları'},
 {src:'/b60-11.webp',alt:'Ecoline B60 ölçüleri'},
 {src:'/b60-12.webp',alt:'Ecoline B60 öne çıkan özellikleri'},
 {src:'/b60-13.webp',alt:'Ecoline B60 ürün ayrıntıları'},
];
const c70Gallery=[
 {src:'/c70-showcase.webp',alt:'Berker Ecoline C70 vitrin görseli'},
 {src:'/c70-01.webp',alt:'Ecoline C70 direksiyon ve kontrol paneli'},
 {src:'/c70-02.webp',alt:'Ecoline C70 arka kapak açık görünüm'},
 {src:'/c70-03.webp',alt:'Ecoline C70 arkadan görünüm'},
 {src:'/c70-04.webp',alt:'Ecoline C70 gerçek saha yan görünümü'},
 {src:'/c70-05.webp',alt:'Ecoline C70 önden gerçek ürün görünümü'},
 {src:'/c70-06.webp',alt:'Ecoline C70 beyaz fonda sol yan görünüm'},
 {src:'/c70-07.webp',alt:'Ecoline C70 beyaz fonda ön yan görünüm'},
 {src:'/c70-08.webp',alt:'Ecoline C70 beyaz fonda sağ yan görünüm'},
 {src:'/c70-09.webp',alt:'Ecoline C70 stüdyo ön yan görünüm'},
 {src:'/c70-10.webp',alt:'Ecoline C70 stüdyo ön görünüm'},
];
const b45Gallery=[
 {src:'/b45-showcase.webp',alt:'Berker Ecoline B45 vitrin görseli'},
 {src:'/b45-01.webp',alt:'Ecoline B45 çoklu renk seçenekleri'},
 {src:'/b45-02.webp',alt:'Ecoline B45 kontrol paneli'},
 {src:'/b45-03.webp',alt:'Ecoline B45 temiz ve kirli su tankları'},
 {src:'/b45-04.webp',alt:'Ecoline B45 teknik özellik tanıtımı'},
 {src:'/b45-05.webp',alt:'Ecoline B45 iş gücü verimliliği karşılaştırması'},
 {src:'/b45-06.webp',alt:'Ecoline B45 profesyonel ürün ayrıntıları'},
 {src:'/b45-07.webp',alt:'Ecoline B45 kullanım ve performans özellikleri'},
];
const machines:Machine[]=[
 {slug:'ecoline-b60-zemin-temizleme-makinasi',name:'Berker Ecoline B60',kind:'İtmeli',fit:'Günlük profesyonel temizlik için akülü ve kompakt çözüm',area:'AVM, fabrika, hastane, havalimanı, depo, istasyon ve oteller',image:'/b60-showcase.webp',gallery:b60Gallery,description:'Ecoline B60, itmeli ve bataryalı yapısıyla günlük zemin temizliğini kolaylaştıran profesyonel bir zemin temizleme makinasıdır. Jel veya lityum akü seçenekleri, akıllı şarj cihazı ve kirli su seviye sensörüyle kontrollü kullanım sunar.',features:['510 mm fırça ve 830 mm silme genişliği','55 litre temiz, 60 litre kirli su tankı','Jel veya lityum akü seçeneği','Akıllı şarj cihazı ve su seviyesi sensörü','Ametek marka 550 W vakum motoru'],specs:[['Model','Ecoline B60'],['Fırça genişliği','510 mm'],['Silme genişliği','830 mm'],['Temiz su tankı','55 litre'],['Kirli su tankı','60 litre'],['Çalışma kapasitesi','2000 m²/saat'],['Voltaj','24 V'],['Vakum motoru','550 W'],['Fırça motoru','700 W'],['Çalışma süresi','4 saatten fazla'],['Boyutlar','1270 × 550 × 1090 mm']]},
 {slug:'ecoline-b250-binicili-zemin-temizleme-otomati',name:'Berker Ecoline B250',kind:'Binicili',fit:'Geniş alanlarda yüksek kapasiteli zemin yıkama ve kirli su toplama',area:'AVM, istasyon, otopark, süpermarket ve fabrika atölyeleri',image:'/b250-showcase.webp',gallery:b250Gallery,description:'Ecoline B250; geniş çalışma alanları için tasarlanmış, binicili tip profesyonel zemin temizleme otomatıdır. Kimyasal karışımlı suyu zemine iletip fırçalama yaparken, arka emiş sistemi kirli suyu ayrı haznede toplar.',features:['1040 mm fırçalama ve 1200 mm silme genişliği','230 litre temiz, 235 litre kirli su tankı','Akıllı şarj cihazı ile otomatik akım kesme','Kirli su tankında seviye sensörü ve motor koruması','Saatte 9450 m² çalışma kapasitesi'],specs:[['Model','Ecoline B250'],['Fırça genişliği','1040 mm'],['Silme genişliği','1200 mm'],['Temiz su tankı','230 litre'],['Kirli su tankı','235 litre'],['Çalışma kapasitesi','9450 m²/saat'],['Voltaj','36 V'],['Vakum motoru','2 × 550 W'],['Fırça motoru','2 × 550 W'],['Yürüyüş motoru','1200 W'],['Çalışma süresi','6 saatten fazla'],['Boyut / ağırlık','1800 × 1180 × 1480 mm / 650 kg']]},
 {slug:'berker-ecoline-c70-binicili-zemin-yikama-makinasi',name:'Berker Ecoline C70',kind:'Binicili',fit:'Çift fırçalı, konforlu ve yüksek verimli zemin yıkama çözümü',area:'Süpermarket, fabrika atölyesi, depo ve geniş ticari alanlar',image:'/c70-showcase.webp',gallery:c70Gallery,description:'Ecoline C70; süpermarketler, fabrika atölyeleri, depolar ve geniş ticari alanlarda kullanılmak üzere tasarlanmış çift fırçalı binicili zemin yıkama makinasıdır. Elektrikli piston sistemi fırça ve vakum grubunu indirerek temizliğe başlamayı kolaylaştırır.',features:['700 mm fırça ve 1030 mm silme genişliği','85 litre temiz, 90 litre kirli su tankı','Ametek marka sessiz emiş motoru','Elektrikli pistonlu fırça ve vakum sistemi','Akıllı şarj cihazı ve su seviyesi sensörü'],specs:[['Model','Ecoline C70'],['Fırça genişliği','700 mm'],['Silme genişliği','1030 mm'],['Temiz su tankı','85 litre'],['Kirli su tankı','90 litre'],['Çalışma kapasitesi','4500 m²/saat'],['Voltaj','24 V'],['Vakum motoru','550 W'],['Fırça motoru','2 × 400 W'],['Yürüyüş motoru','500 W'],['Çalışma süresi','4 saatten fazla'],['Boyut / ağırlık','1400 × 1030 × 1100 mm / 280 kg']]},
 {slug:'berker-ecoline-b45-akulu-itmeli-zemin-otomati',name:'Berker Ecoline B45',kind:'İtmeli',fit:'Orta ölçekli ticari alanlar için pratik ve verimli günlük temizlik',area:'Fabrika, depo, süpermarket, otopark, otel, AVM, okul, hastane ve ofisler',image:'/b45-showcase.webp',gallery:b45Gallery,description:'Ecoline B45; günlük ticari zemin temizliği için tasarlanmış akülü ve arkadan itmeli zemin otomatıdır. Kararlı performansı, kolay kullanımı, geniş ağızlı temiz su girişi ve bakım odaklı yapısıyla orta ölçekli alanlarda düzenli temizlik sağlar.',features:['510 mm fırça ve 800 mm silici genişliği','40 litre temiz, 45 litre kirli su tankı','24 V 50 Ah akü sistemi','3–4 saat çalışma desteği','Manuel fırça ve vakum kaldırma sistemi'],specs:[['Model','Ecoline B45'],['Güç kaynağı','24 V'],['Çalışma süresi','3–4 saat'],['Kirli / temiz su tankı','45 / 40 litre'],['Çalışma kapasitesi','2150 m²/saat'],['Vakum motoru','550 W'],['Fırça motoru','600 W'],['Fırça genişliği','510 mm'],['Silici genişliği','800 mm'],['Ses seviyesi','68 dB'],['Makine ağırlığı','65 kg / akü hariç']]},
 {slug:'ecoline-b140-binicili-zemin-temizleme-makinasi',name:'Berker Ecoline B140',kind:'Binicili',fit:'Dar ve kalabalık alanlarda sessiz, güçlü ve çevik zemin temizliği',area:'Okul, ofis, hastane, süpermarket, fabrika, depo, AVM ve oteller',image:'/b140-showcase.webp',gallery:b140Gallery,description:'Ecoline B140; endüstriyel ve ticari zeminlerde kullanılmak üzere tasarlanmış binicili zemin temizleme makinasıdır. Kompakt sürüş yapısı, sessiz çalışma yaklaşımı ve tek tuşla fırça ile vakum indirme sistemi sayesinde dar veya yoğun alanlarda kontrollü temizlik sağlar.',features:['860 mm fırça ve 1150 mm silme genişliği','125 litre temiz, 130 litre kirli su tankı','Yüzde 16 eğim tırmanma kabiliyeti','Elektrikli piston ile tek tuşla fırça ve vakum indirme','Akıllı şarj cihazı ve su seviyesi sensörü'],specs:[['Model','Ecoline B140'],['Fırça genişliği','860 mm'],['Silme genişliği','1150 mm'],['Temiz su tankı','125 litre'],['Kirli su tankı','130 litre'],['Çalışma kapasitesi','5500 m²/saat'],['Voltaj','24 V'],['Vakum motoru','550 W'],['Fırça motoru','2 × 500 W'],['Yürüyüş motoru','800 W'],['Çalışma süresi','5 saatten fazla'],['Boyut / ağırlık','1665 × 910 × 1295 mm / 295 kg']]},
];
const productPriority=['ecoline-b250-binicili-zemin-temizleme-otomati','ecoline-b140-binicili-zemin-temizleme-makinasi','ecoline-b60-zemin-temizleme-makinasi','berker-ecoline-c70-binicili-zemin-yikama-makinasi','berker-ecoline-b45-akulu-itmeli-zemin-otomati'];
machines.sort((a,b)=>{const ai=productPriority.indexOf(a.slug),bi=productPriority.indexOf(b.slug);return (ai<0?999:ai)-(bi<0?999:bi)});
type MachineAdminState={hidden:string[];custom:Machine[]};
const machineAdminKey='zy-machine-admin';
function useManagedMachines(){
 return machines;
}
const sectorData=[['fabrika','Fabrikalar'],['avm','AVM’ler'],['depo','Depolar'],['otopark','Otoparklar'],['hastane','Hastaneler'],['otel','Oteller'],['market','Marketler'],['okul','Okullar'],['belediye','Belediyeler'],['lojistik','Lojistik Merkezleri']];
const posts=[
 ['zemin-tipine-gore-makine-secimi','Zemin Tipine Göre Makine Seçimi','Kaplama, kir türü, geçiş genişliği ve çalışma düzenini tek kararda birleştirin.'],
 ['kiralama-mi-satin-alma-mi','Kiralama mı, Satın Alma mı?','Kullanım sıklığı ve bakım sorumluluğuna göre iki modeli değerlendirin.'],
 ['temizlik-makinesi-bakim-plani','Sürdürülebilir Bakım Planı','Günlük kontrolden servis kaydına uzanan uygulanabilir bir düzen kurun.'],
 ['fabrika-zemin-temizligi-planlama','Fabrika Zemin Temizliği Nasıl Planlanır?','Üretim akışını aksatmadan vardiya, güvenli çalışma bölgesi ve kir yoğunluğuna göre uygulanabilir bir temizlik planı hazırlayın.'],
 ['depo-koridorlarinda-makine-secimi','Depo Koridorlarında Makine Seçimi','Raf araları, dönüş noktaları, kapı açıklıkları ve sevkiyat trafiğini birlikte değerlendirerek uygun makine sınıfını belirleyin.'],
 ['gunluk-makine-kontrol-listesi','Günlük Makine Kontrol Listesi','Her vardiya öncesi ve sonrasında uygulanabilecek kısa kontrollerle kullanım düzenini koruyun ve olası aksaklıkları erkenden fark edin.'],
 ['zemin-yikama-makinesi-nasil-secilir','Zemin Yıkama Makinesi Nasıl Seçilir?','Alan, geçiş genişliği, zemin yapısı ve çalışma düzenini birlikte değerlendirerek doğru makine sınıfını belirleyin.'],
 ['binicili-ve-itmeli-makine-farklari','Binicili ve İtmeli Makine Arasındaki Farklar','Manevra ihtiyacı, saha büyüklüğü ve operatör çalışma süresine göre iki makine sınıfını karşılaştırın.'],
 ['zemin-yikama-makinesi-bakimi','Zemin Yıkama Makinesi Günlük Bakımı','Tank, silici, fırça ve akü kontrollerini düzenli bir sıraya koyarak temizlik performansını koruyun.'],
];

function Header(){return <><div className="siteTop"><div><span>◇ Türkiye Geneli Hizmet</span><span>◉ Uzman Teknik Destek</span><span>◇ Yedek Parça Süreci</span></div><div><a href="https://wa.me/905375223946" onClick={()=>event('whatsapp_click')}>◉ WhatsApp</a><a href="/iletisim">İletişim Talebi</a></div></div><header className="siteHeader"><details className="mobileMenu"><summary aria-label="Menüyü aç">☰</summary><div><a href="/">Ana Sayfa</a><a href="/zemin-yikama-makineleri">Zemin Yıkama Makineleri</a><a href="/kiralama">Hizmetler</a><a href="/sektorler">Sektörel Çözümler</a><a href="/yedek-parca">Yedek Parça</a><a href="/blog">Blog</a><a href="/iletisim">İletişim</a></div></details><a className="siteLogo" href="/"><b>ZEMİN YIKAMA</b><span>MAKİNELERİ</span></a><nav><a href="/">ANA SAYFA</a><a href="/zemin-yikama-makineleri">ZEMİN YIKAMA MAKİNELERİ⌄</a><a href="/kiralama">HİZMETLER⌄</a><a href="/sektorler">SEKTÖREL ÇÖZÜMLER⌄</a><a href="/yedek-parca">YEDEK PARÇA</a><a href="/blog">BLOG</a><a href="/iletisim">İLETİŞİM</a></nav><a className="blueBtn" href="/teklif-al">TEKLİF AL</a></header></>}
function Sticky(){return <div className="siteSticky"><a href="tel:+905375223946" onClick={()=>event('click_to_call')}>☎<span><b>HEMEN ARA</b><small>TELEFON TALEBİ</small></span></a><a href="https://wa.me/905375223946" onClick={()=>event('whatsapp_click')}>◉<span><b>WHATSAPP</b><small>HIZLI BİLGİ AL</small></span></a><a href="/teklif-al" onClick={()=>event('cta_click',{place:'sticky'})}>▣<span><b>TEKLİF AL</b><small>ÜCRETSİZ TALEP</small></span></a></div>}
function Footer(){return <footer className="siteFooter"><div><a className="siteLogo light" href="/"><b>ZEMİN YIKAMA</b><span>MAKİNELERİ</span></a><p>Profesyonel zemin temizliği için makine seçimi, kiralama, servis ve yedek parça süreçleri.</p></div><div><b>ZEMİN YIKAMA MAKİNELERİ</b><a href="/zemin-yikama-makineleri/binicili">Binicili</a><a href="/zemin-yikama-makineleri/iticili">İtmeli</a><a href="/zemin-yikama-makineleri/supuruculer">Süpürücüler</a></div><div><b>YEDEK PARÇA</b><a href="/yedek-parca">Yedek Parçalar</a><a href="/sepet">Sepetim</a><a href="/admin">Yedek Parça Yönetimi</a></div><div><b>HIZLI ERİŞİM</b><a href="/makine-secici">Makine Seçici</a><a href="/karsilastir">Karşılaştırma</a><a href="/blog">Bilgi Merkezi</a><a href="/teklif-al">Teklif Al</a></div><small className="footerNote">© Zemin Yıkama Makineleri · Model özellikleri, fiyat ve ticari koşullar teklif aşamasında doğrulanır. <a href="https://www.instagram.com/d.ijitaluzman/" target="_blank" rel="noopener noreferrer">ByDjtluzman</a></small></footer>}
function Shell({children}:{children:React.ReactNode}){return <main className="site"><Header/>{children}<Footer/><Sticky/></main>}
function Breadcrumb({items}:{items:string[]}){return <nav className="breadcrumb"><a href="/">Ana Sayfa</a>{items.map(x=><span key={x}>› {x}</span>)}</nav>}
function Hero({eyebrow,title,text}:{eyebrow:string,title:string,text:string}){return <section className="subHero"><div className="subHeroShade"/><div className="subHeroInner"><Breadcrumb items={[title]}/><strong>{eyebrow}</strong><h1>{title}</h1><p>{text}</p><a className="blueBtn" href="/teklif-al">ÜCRETSİZ TEKLİF AL</a></div></section>}
function Benefits(){return <section className="darkBenefits">{[['♙','Uzman Yönlendirme'],['◈','Geniş Çözüm Yelpazesi'],['✹','Teknik Servis Desteği'],['⚙','Yedek Parça Süreci'],['◉','Satış Sonrası Destek']].map(x=><div key={x[1]}><i>{x[0]}</i><span><b>{x[1]}</b><small>Talebinize göre planlı süreç</small></span></div>)}</section>}
function BottomCTA(){return <section className="bottomCta"><div><small>DOĞRU MAKİNEYİ BİRLİKTE BELİRLEYELİM</small><h2>Sahanız için uygun çözümü bulun.</h2><p>Alan, zemin ve çalışma düzeninizi paylaşın; doğrulanmış bilgilerle ilerleyin.</p></div><a className="greenBtn" href="/teklif-al">HEMEN TEKLİF AL →</a></section>}
function MachineGraphic({tone=0}:{tone?:number}){return <div className={`cssMachine tone${tone}`}><i/><em/><b/><span/></div>}

function Catalog({category}:{category?:string}){const managedMachines=useManagedMachines();const title=category==='binicili'?'Binicili Zemin Yıkama Makineleri':category==='iticili'?'İtmeli Zemin Yıkama Makineleri':category==='supuruculer'?'Endüstriyel Süpürücüler':'Zemin Yıkama Makineleri';const shown=managedMachines.filter(m=>!category||(category==='binicili'?m.kind==='Binicili':category==='iticili'?['İtmeli','Akülü'].includes(m.kind):m.kind==='Süpürücü'));return <Shell><Hero eyebrow="PROFESYONEL MAKİNE ÇÖZÜMLERİ" title={title} text="Sahanızın yapısına göre makine sınıflarını inceleyin. Teknik değerler ve ticari koşullar talep sırasında doğrulanır."/><Benefits/><section className="pageSection"><div className="sectionTitle"><div><small>MAKİNE KATEGORİLERİ</small><h2>İhtiyacınıza göre filtreleyin</h2></div><div className="pills"><a href="/zemin-yikama-makineleri">Tümü</a><a href="/zemin-yikama-makineleri/binicili">Binicili</a><a href="/zemin-yikama-makineleri/iticili">İtmeli</a><a href="/zemin-yikama-makineleri/supuruculer">Süpürücü</a></div></div><div className="machineGrid">{shown.map((m,i)=><article className="machineCard" key={m.slug}><div className="cardVisual">{m.image?<img src={m.image} alt={`${m.name} binicili zemin temizleme makinesi`}/>:<MachineGraphic tone={i}/>}<span>{m.kind}</span></div><small>{m.kind.toUpperCase()}</small><h2>{m.name}</h2><p>{m.fit}</p><dl><div><dt>Kullanım alanı</dt><dd>{m.area}</dd></div><div><dt>Bilgi durumu</dt><dd>{m.specs?'Teknik veriler eklendi':'Teklif sırasında teyit edilir'}</dd></div></dl><div className="cardButtons"><a className="blueBtn" href={`/urun/${m.slug}`}>İNCELE</a><a href="/karsilastir">KARŞILAŞTIR →</a></div></article>)}</div></section><BottomCTA/></Shell>}
function Product({slug}:{slug:string}){const managedMachines=useManagedMachines();const m=managedMachines.find(x=>x.slug===slug)||managedMachines[0]||machines[0];const [activeImage,setActiveImage]=useState<{src:string;alt:string}|null>(null);return <Shell><section className="productHero"><div><Breadcrumb items={['Makineler',m.name]}/><strong>{m.kind.toUpperCase()} ZEMİN TEMİZLEME</strong><h1>{m.name}</h1><p>{m.description||m.fit}</p><div className="heroActions"><a className="blueBtn" href="/teklif-al">TEKLİF AL</a><a className="outlineBtn" href="/karsilastir">KARŞILAŞTIR</a></div></div><div className="productMachine">{m.image&&<img src={m.image} alt={`${m.name} zemin temizleme makinesi`}/>}</div></section><Benefits/><section className="pageSection productIntro"><article><small>ÜRÜN DETAYLARI</small><h2>{m.name} ile profesyonel zemin temizliği</h2><p>{m.description}</p><h3>Öne çıkan özellikler</h3><ul>{m.features?.map(x=><li key={x}>{x}</li>)}</ul></article></section>{m.specs&&<section className="techSection"><h2>TEKNİK ÖZELLİKLER</h2><div className="techLayout"><dl>{m.specs.map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl>{m.image&&<img src={m.image} alt={`${m.name} teknik özellik görünümü`}/>}</div><a className="greenBtn" href="/teklif-al">FİYAT BİLGİSİ AL →</a></section>}{m.gallery&&<section className="productGallery"><div><small>{m.name.toUpperCase()} GALERİ</small><h2>Makineyi tüm ayrıntılarıyla inceleyin</h2><p>Bir görsele dokunarak aynı sayfa üzerinde büyük boy açabilirsiniz.</p></div><div className="galleryGrid">{m.gallery.map((g,i)=><button type="button" onClick={()=>setActiveImage(g)} key={g.src} aria-label={`${g.alt} görselini büyüt`}><img src={g.src} alt={g.alt} loading={i<4?'eager':'lazy'}/><span>{String(i+1).padStart(2,'0')}</span></button>)}</div></section>}{activeImage&&<div className="imageLightbox" role="dialog" aria-modal="true" aria-label={activeImage.alt} onClick={()=>setActiveImage(null)}><button type="button" className="lightboxClose" onClick={()=>setActiveImage(null)} aria-label="Görseli kapat">×</button><div onClick={e=>e.stopPropagation()}><img src={activeImage.src} alt={activeImage.alt}/><p>{activeImage.alt}</p></div></div>}<BottomCTA/></Shell>}
const services:Record<string,{title:string;eyebrow:string;text:string;steps:string[]}>={
 kiralama:{title:'Zemin Yıkama Makinesi Kiralama',eyebrow:'ESNEK KULLANIM MODELİ',text:'Dönemsel veya sürekli ihtiyacınızı paylaşın; saha ve çalışma düzeninize uygun kiralama yaklaşımını birlikte netleştirelim.',steps:['Saha ve ihtiyaç kaydı','Makine sınıfının belirlenmesi','Teslim ve kullanım planı']},
 servis:{title:'Teknik Servis ve Bakım',eyebrow:'PLANLI DESTEK SÜRECİ',text:'Arıza, bakım ve kontrol taleplerini kayıtlı bir akışla değerlendirin; plansız duruş riskini azaltmaya yardımcı olun.',steps:['Talep ve makine kaydı','Kontrol ve çözüm planı','İşlem sonrası bilgilendirme']},
 'yedek-parca':{title:'Zemin Yıkama Makinesi Yedek Parça',eyebrow:'UYUMLULUK TEYİTLİ SÜREÇ',text:'Makine ve ihtiyaç duyulan parça bilgilerini iletin; uyumluluk doğrulandıktan sonra tedarik adımına geçin.',steps:['Model bilgisinin alınması','Parça uyumluluğunun kontrolü','Tedarik yönlendirmesi']},
 'ikinci-el':{title:'İkinci El Zemin Yıkama Makineleri',eyebrow:'KONTROLLÜ ALTERNATİFLER',text:'Mevcut durumu açıkça belirtilen seçenekleri inceleyin; stok ve koşulları talep sırasında doğrulayın.',steps:['İhtiyaç profilinin çıkarılması','Mevcut seçeneklerin paylaşılması','Durum ve kapsam teyidi']}
};
const serviceGuides=[
 {href:'/blog/zemin-yikama-makinesi-nasil-secilir',tag:'SEÇİM REHBERİ',title:'Zemin yıkama makinesi nasıl seçilir?',text:'Alan büyüklüğü, geçiş genişliği, zemin kaplaması, kir türü ve çalışma süresini birlikte değerlendirin.'},
 {href:'/blog/binicili-ve-itmeli-makine-farklari',tag:'MAKİNE TÜRLERİ',title:'Binicili mi, itmeli mi?',text:'Manevra ihtiyacı ve saha büyüklüğüne göre iki profesyonel makine sınıfının kullanım farklarını inceleyin.'},
 {href:'/blog/zemin-yikama-makinesi-bakimi',tag:'BAKIM NOTLARI',title:'Verimli kullanım için günlük bakım',text:'Tank, silici, fırça ve akü kontrollerini düzenli bir sıraya koyarak kullanım performansını koruyun.'}
];
function Service({kind}:{kind:string}){const s=services[kind];return <Shell><Hero eyebrow={s.eyebrow} title={s.title} text={s.text}/><Benefits/><section className="pageSection serviceIntro"><div><small>SÜREÇ YAKLAŞIMI</small><h2>Sade, şeffaf ve sahaya odaklı.</h2><p>Genel vaatler yerine ihtiyacınıza göre netleşen adımlarla ilerleyin. Her teknik ve ticari detay, ilgili makine ve saha bilgisi üzerinden doğrulanır.</p></div><div className="processGrid">{s.steps.map((x,i)=><article key={x}><span>0{i+1}</span><h3>{x}</h3><p>İlgili bilgiler kaydedilir, kontrol edilir ve sonraki adım açıkça paylaşılır.</p></article>)}</div></section><section className="imageBand"><div><strong>OPERASYONU DURDURMADAN</strong><h2>Temizlik sürecinizi planlayın.</h2><p>İhtiyaç türünü ve çalışma düzenini formda belirtin.</p></div></section>{kind==='kiralama'&&<><section className="homeKnowledge" aria-labelledby="zemin-yikama-nedir"><article className="knowledgeMain"><small>BİLGİ MERKEZİ</small><h2 id="zemin-yikama-nedir">Zemin Yıkama Makinesi Nedir?</h2><p>Zemin yıkama makineleri; fabrika, depo, AVM, otel, hastane, market, mağaza ve otopark gibi geniş alanlarda zeminlerin hızlı ve profesyonel şekilde temizlenmesi için kullanılan endüstriyel temizlik makineleridir.</p><p>Aynı işlem içinde zemini fırçalar, kirli suyu vakumlar ve yüzeyin daha kısa sürede kullanıma hazır hale gelmesine yardımcı olur. Akülü, elektrikli, itmeli ve binicili seçenekler farklı saha ihtiyaçlarına karşılık verir.</p><h3>Zemin Yıkama Makinelerinin Avantajları</h3><ul><li>Geniş alanların daha kısa sürede temizlenmesine yardımcı olur.</li><li>Zorlu kirlerde kontrollü fırçalama sağlar.</li><li>Su ve temizlik kimyasalının planlı kullanımını destekler.</li><li>Kirli suyu vakumlayarak zeminin daha hızlı kurumasına yardımcı olur.</li><li>Profesyonel ve homojen temizlik sonucu sunar.</li></ul><h3>Nerelerde Kullanılır?</h3><p>Fabrikalar, üretim tesisleri, depolar, lojistik merkezleri, AVM’ler, marketler, oteller, hastaneler, okullar ve otoparklarda kullanılabilir.</p></article><aside className="knowledgeAside"><h2>Doğru makine, sahaya göre belirlenir</h2><p>Alanınızı ve çalışma düzeninizi paylaşın; uygun makine sınıfını birlikte daraltalım.</p><a href="/makine-secici">HANGİ MAKİNE BANA UYGUN? →</a></aside></section><section className="homeGuideSection"><div className="homeGuideHeading"><small>ÖZGÜN REHBERLER</small><h2>Profesyonel zemin temizliği için kısa okumalar</h2></div><div className="homeGuideGrid">{serviceGuides.map(g=><a href={g.href} key={g.href}><small>{g.tag}</small><h3>{g.title}</h3><p>{g.text}</p><b>REHBERİ OKU →</b></a>)}</div></section></>}<BottomCTA/></Shell>}
function Sectors({slug}:{slug?:string}){const current=sectorData.find(x=>x[0]===slug);if(current)return <Shell><Hero eyebrow="SEKTÖREL TEMİZLİK ÇÖZÜMLERİ" title={`${current[1]} İçin Zemin Temizliği`} text={`${current[1]} için zemin, trafik, çalışma saati ve temizlik hedefini birlikte değerlendiren saha odaklı yaklaşım.`}/><Benefits/><section className="pageSection twoColumns"><article><small>SAHAYA GÖRE PLANLAMA</small><h2>Tek bir ölçü yetmez.</h2><p>{current[1]} için makine seçimi yalnızca metrekareye göre yapılmamalıdır. Dar geçişler, dönüş noktaları, zemin kaplaması, baskın kir türü ve temizliğe ayrılan süre birlikte ele alınır.</p><h3>Değerlendirilecek başlıklar</h3><ul><li>Zemin kaplaması ve eğim durumu</li><li>Yaya veya araç trafik yoğunluğu</li><li>Temizlik saatleri ve güvenli çalışma alanı</li><li>Depolama, şarj ve günlük bakım noktası</li></ul></article><aside><h3>Alanınızı kısaca tarif edin</h3><p>Doğrulanmamış teknik değerler vermeden uygun makine sınıfını birlikte daraltalım.</p><a className="greenBtn" href="/teklif-al">SAHA TALEBİ OLUŞTUR →</a></aside></section><BottomCTA/></Shell>;return <Shell><Hero eyebrow="SEKTÖREL ÇÖZÜMLER" title="Her Sektöre Özel Zemin Temizliği" text="Farklı saha koşulları için aynı makineyi önermek yerine, kullanım düzenine göre doğru başlangıç noktasını bulun."/><section className="pageSection"><div className="sectorPageGrid">{sectorData.map((s,i)=><a href={`/sektorler/${s[0]}`} key={s[0]}><div className={`sectorImage sector${i}`}/><div><h2>{s[1]}</h2><p>Sahaya özel seçim kriterlerini inceleyin.</p><b>DETAYLARI GÖR →</b></div></a>)}</div></section><Benefits/><BottomCTA/></Shell>}
function Blog({slug}:{slug?:string}){const p=posts.find(x=>x[0]===slug);if(p)return <Shell><article className="articlePage"><Breadcrumb items={['Blog',p[1]]}/><strong>ÖZGÜN REHBER</strong><h1>{p[1]}</h1><p className="articleLead">{p[2]}</p><div className="articleCover"/><h2>Kararı sahadan başlatın</h2><p>Makine seçiminde tek bir ölçüte güvenmek yanıltıcı olabilir. Kullanım alanının net büyüklüğü kadar geçişler, dönüş noktaları, yüzey yapısı ve temizlik için ayrılan zaman da değerlendirilmelidir.</p><h2>Toplam kullanım düzenini düşünün</h2><p>Makinenin gün içinde nasıl kullanılacağı, nerede saklanacağı, günlük kontrolleri kimin yapacağı ve servis kaydının nasıl tutulacağı seçimin sürdürülebilirliğini etkiler.</p><blockquote>Modele özel teknik bilgiler üretici belgeleri ve teklif kapsamıyla teyit edilmelidir.</blockquote><h2>Uygulanabilir kontrol listesi</h2><ol><li>Net temizlenecek alanı belirleyin.</li><li>En dar geçiş ve dönüş alanını ölçün.</li><li>Zemin ve baskın kir türünü not edin.</li><li>Temizlik zaman aralığını planlayın.</li><li>Bakım sorumluluğunu tanımlayın.</li></ol><nav className="articleLinks" aria-label="İlgili site bağlantıları"><h2>İlgili çözümleri inceleyin</h2><a href="/makineler">Tüm zemin yıkama makineleri</a><a href="/makineler/binicili">Binicili zemin yıkama makineleri</a><a href="/makineler/iticili">İtmeli zemin yıkama makineleri</a><a href="/sektorler">Sektörel temizlik çözümleri</a><a href="/servis">Teknik servis ve bakım</a><a href="/yedek-parca">Yedek parça desteği</a><a href="/teklif-al">Makine için teklif alın</a></nav></article><BottomCTA/></Shell>;return <Shell><Hero eyebrow="BİLGİ MERKEZİ" title="Daha Bilinçli Bir Seçim İçin" text="Sıfırdan hazırlanmış, karar süreçlerini kolaylaştıran özgün rehberler ve saha notları."/><section className="pageSection blogGrid">{posts.map((p,i)=><a href={`/blog/${p[0]}`} key={p[0]}><div className={`blogPic blog${i}`}/><small>REHBER</small><h2>{p[1]}</h2><p>{p[2]}</p><b>OKUMAYA DEVAM ET →</b></a>)}</section><Benefits/></Shell>}
function Quote(){
 const [done,setDone]=useState(false);
 function submit(e:FormEvent<HTMLFormElement>){
  e.preventDefault();
  const data=Object.fromEntries(new FormData(e.currentTarget).entries()) as Record<string,string>;
  const createdAt=new Date().toISOString();
  const saved=JSON.parse(localStorage.getItem('zemin-yikama-teklifleri')||'[]');
  localStorage.setItem('zemin-yikama-teklifleri',JSON.stringify([...saved,{...data,createdAt}]));
  const whatsappMessage=[
   'Merhaba, zeminyikama.com üzerinden teklif talebi oluşturuldu.',
   '',
   `Ad / Firma: ${data.name||'-'}`,
   `İletişim: ${data.contact||'-'}`,
   `İletişim tercihi: ${data.channel||'-'}`,
   `İhtiyaç türü: ${data.need||'-'}`,
   `Alan ölçeği: ${data.area||'-'}`,
   '',
   'Saha ve ihtiyaç açıklaması:',
   data.message||'-',
  ].join('\n');
  event('generate_lead',{form:'quote',destination:'whatsapp'});
  window.open(`https://wa.me/905375223946?text=${encodeURIComponent(whatsappMessage)}`,'_blank','noopener,noreferrer');
  setDone(true);
 }
 return <Shell><Hero eyebrow="ÜCRETSİZ TALEP" title="Teklif Formu" text="Bilgilerinizi doldurun; teklif talebiniz WhatsApp üzerinden doğrudan ekibimize iletilsin."/><section className="formSection">{done?<div className="formDone"><b>WhatsApp teklif mesajınız hazırlandı.</b><p>Mesaj, 0537 522 39 46 numaralı WhatsApp sohbetinde açıldı. WhatsApp ekranındaki gönder düğmesine basarak talebinizi iletebilirsiniz.</p><a href="https://wa.me/905375223946">WHATSAPP’I TEKRAR AÇ →</a></div>:<form onSubmit={submit}><div className="formHeader"><small>İHTİYAÇ BİLGİLERİ</small><h2>Size uygun çözümü belirleyelim.</h2><p>Form gönderildiğinde bütün bilgileriniz WhatsApp mesajına dönüştürülür.</p></div><div className="formGrid"><label>Adınız / Firma adınız<input required name="name"/></label><label>Telefon veya e-posta<input required name="contact" type="text"/></label><label>İletişim tercihi<select name="channel"><option>Telefon</option><option>WhatsApp</option><option>E-posta</option></select></label><label>İhtiyaç türü<select name="need"><option>Satın alma</option><option>Kiralama</option><option>Servis</option><option>Yedek parça</option><option>İkinci el</option></select></label><label>Alan ölçeği<select name="area"><option>Henüz bilmiyorum</option><option>Küçük</option><option>Orta</option><option>Geniş</option></select></label><label className="wide">Saha ve ihtiyaç açıklaması<textarea rows={5} required name="message"/></label><label className="check wide"><input type="checkbox" required name="consent"/> Talebimin WhatsApp üzerinden iletilmesini kabul ediyorum.</label></div><button className="greenBtn" type="submit">WHATSAPP’TAN TEKLİF GÖNDER →</button></form>}</section></Shell>
}
function Selector(){const [area,setArea]=useState('');const [passage,setPassage]=useState('');const answer=useMemo(()=>!area||!passage?null:area==='large'&&passage!=='narrow'?machines[2]:area==='small'?machines[0]:machines[1],[area,passage]);return <Shell><Hero eyebrow="MAKİNE SEÇİCİ" title="Hangi Makine Bana Uygun?" text="İki temel soruyla uygun makine sınıfı için başlangıç önerisi alın. Son karar saha bilgileri doğrulandıktan sonra verilmelidir."/><section className="selector"><div><label><span>01</span>Alan ölçeği<select value={area} onChange={e=>setArea(e.target.value)}><option value="">Seçin</option><option value="small">Küçük</option><option value="medium">Orta</option><option value="large">Geniş</option></select></label><label><span>02</span>Dar geçişler<select value={passage} onChange={e=>setPassage(e.target.value)}><option value="">Seçin</option><option value="narrow">Yoğun</option><option value="mixed">Kısmen</option><option value="open">Saha açık</option></select></label></div><aside>{answer?<><small>BAŞLANGIÇ ÖNERİSİ</small><h2>{answer.name}</h2><p>{answer.fit}. Bu sonuç bağlayıcı teknik öneri değildir.</p><a className="greenBtn" href="/teklif-al">UZMAN DEĞERLENDİRMESİ →</a></>:<><small>SONUÇ ALANI</small><h2>İki seçimi tamamlayın</h2><p>Yanıtlarınıza göre uygun başlangıç sınıfı burada görünecek.</p></>}</aside></section><Benefits/></Shell>}
function Compare(){return <Shell><Hero eyebrow="MAKİNE KARŞILAŞTIRMA" title="Makine Sınıflarını Yan Yana Görün" text="Kesin model değerleri yerine karar sürecinde anlamlı olan kullanım farklarını karşılaştırın."/><section className="compare"><table><thead><tr><th>Karar başlığı</th>{machines.slice(0,3).map(m=><th key={m.slug}>{m.name}</th>)}</tr></thead><tbody><tr><th>Tür</th>{machines.slice(0,3).map(m=><td key={m.slug}>{m.kind}</td>)}</tr><tr><th>Alan yaklaşımı</th>{machines.slice(0,3).map(m=><td key={m.slug}>{m.area}</td>)}</tr><tr><th>Kullanım odağı</th>{machines.slice(0,3).map(m=><td key={m.slug}>{m.fit}</td>)}</tr><tr><th>İşlem</th>{machines.slice(0,3).map(m=><td key={m.slug}><a href="/teklif-al">BİLGİ İSTE →</a></td>)}</tr></tbody></table></section><BottomCTA/></Shell>}
function Contact(){return <Shell><Hero eyebrow="İLETİŞİM" title="Size Uygun Kanaldan Ulaşalım" text="Makine, servis, yedek parça ve teklif ihtiyaçlarınız için size uygun iletişim kanalını seçin."/><section className="contactCards"><a href="tel:+905375223946"><img className="contactWordmark" src="/contact-phone.png" alt="Telefon"/><span>HEMEN ARA →</span></a><a href="https://wa.me/905375223946"><img className="contactWordmark" src="/contact-whatsapp.png" alt="WhatsApp"/><span>WHATSAPP’I AÇ →</span></a><a href="/teklif-al"><img className="contactWordmark" src="/contact-quote.png" alt="Teklif Al"/><span>FORMA GİT →</span></a></section><Benefits/></Shell>}
function Landing({rental}:{rental:boolean}){return <Shell><section className="landing"><div><strong>{rental?'KİRALAMA ÇÖZÜMLERİ':'PROFESYONEL MAKİNE ÇÖZÜMLERİ'}</strong><h1>{rental?'Zemin Yıkama Makinesi Kiralama':'Profesyonel Zemin Yıkama Makineleri'}</h1><p>{rental?'Dönemsel veya sürekli kullanım ihtiyacınızı paylaşın; uygun kiralama yaklaşımını birlikte belirleyelim.':'Makine sınıflarını karşılaştırın, sahanıza uygun başlangıç noktasını belirleyin ve teyitli teklif isteyin.'}</p><a className="greenBtn" href="/teklif-al">HIZLI TEKLİF İSTE →</a></div></section><Benefits/><BottomCTA/></Shell>}
function Missing(){return <Shell><section className="missing"><b>404</b><h1>Bu sayfa bulunamadı.</h1><p>Bağlantı değişmiş veya sayfa kaldırılmış olabilir.</p><a className="blueBtn" href="/">ANA SAYFAYA DÖN</a></section></Shell>}

export default function SiteShell({slug=[]}:{slug?:string[]}){const p=slug.join('/');if(p==='yedek-parca'||p==='shop')return <Shell><ShopSystem page="shop"/></Shell>;if(p.startsWith('yedek-parca/urun/')||p.startsWith('shop/urun/'))return <Shell><ShopSystem page="product" slug={slug[2]}/></Shell>;if(p==='sepet')return <Shell><ShopSystem page="cart"/></Shell>;if(p==='odeme')return <Shell><ShopSystem page="checkout"/></Shell>;if(p==='admin')return <ShopSystem page="admin"/>;if(p==='zemin-yikama-makineleri'||p==='makineler')return <Catalog/>;if(p.startsWith('zemin-yikama-makineleri/')||p.startsWith('makineler/'))return <Catalog category={slug[1]}/>;if(p.startsWith('urun/'))return <Product slug={slug[1]}/>;if(services[p])return <Service kind={p}/>;if(p==='sektorler')return <Sectors/>;if(p.startsWith('sektorler/'))return <Sectors slug={slug[1]}/>;if(p==='blog')return <Blog/>;if(p.startsWith('blog/'))return <Blog slug={slug[1]}/>;if(p==='teklif-al')return <Quote/>;if(p==='makine-secici')return <Selector/>;if(p==='karsilastir')return <Compare/>;if(p==='iletisim')return <Contact/>;if(p==='lp/zemin-yikama-makinesi')return <Landing rental={false}/>;if(p==='lp/kiralama')return <Landing rental/>;return <Missing/>}

