import type { Metadata } from 'next';
import Script from 'next/script';
import '@fontsource/roboto-condensed/400.css';
import '@fontsource/roboto-condensed/500.css';
import '@fontsource/roboto-condensed/600.css';
import '@fontsource/roboto-condensed/700.css';
import './globals.css';
export const metadata:Metadata={metadataBase:new URL('https://www.zeminyikama.com'),title:{default:'Zemin Yıkama Makineleri | Satış, Kiralama ve Servis',template:'%s | Zemin Yıkama Makineleri'},description:'Profesyonel zemin yıkama ve temizleme makinelerini inceleyin. Binicili, itmeli ve akülü modeller için satış, kiralama, servis, yedek parça ve teklif seçenekleri.',keywords:['zemin yıkama makineleri','zemin yıkama makinesi','zemin temizleme makinesi','yer yıkama makinesi','binicili zemin yıkama makinesi','itmeli zemin yıkama makinesi','endüstriyel temizlik makineleri'],applicationName:'Zemin Yıkama Makineleri',category:'Endüstriyel temizlik makineleri',icons:{icon:[{url:'/favicon.png',type:'image/png'}],shortcut:'/favicon.png',apple:'/favicon.png'},alternates:{canonical:'/'},openGraph:{title:'Zemin Yıkama Makineleri | Profesyonel Temizlik Çözümleri',description:'Binicili, itmeli ve akülü zemin yıkama makineleri; satış, kiralama, servis ve yedek parça çözümleri.',url:'https://www.zeminyikama.com',siteName:'Zemin Yıkama Makineleri',locale:'tr_TR',type:'website',images:[{url:'/home-product-lineup-v3.png',width:1536,height:1024,alt:'Profesyonel zemin yıkama makineleri'}]},twitter:{card:'summary_large_image',title:'Zemin Yıkama Makineleri',description:'Profesyonel zemin yıkama makineleri, servis ve yedek parça çözümleri.',images:['/home-product-lineup-v3.png']},robots:{index:true,follow:true,googleBot:{index:true,follow:true,'max-image-preview':'large','max-snippet':-1,'max-video-preview':-1}}};
const schema={'@context':'https://schema.org','@graph':[{'@type':'Organization','@id':'https://www.zeminyikama.com/#organization',name:'Zemin Yıkama Makineleri',url:'https://www.zeminyikama.com',logo:'https://www.zeminyikama.com/logo-desktop.png',email:'info@berkermakine.com',contactPoint:{'@type':'ContactPoint',telephone:'+90-537-522-39-46',contactType:'sales',availableLanguage:'Turkish'}},{'@type':'WebSite','@id':'https://www.zeminyikama.com/#website',url:'https://www.zeminyikama.com',name:'Zemin Yıkama Makineleri',publisher:{'@id':'https://www.zeminyikama.com/#organization'},inLanguage:'tr-TR'}]};
export default function RootLayout({children}:{children:React.ReactNode}){return <html lang="tr"><head><link rel="icon" href="/favicon.png?v=20260828" type="image/png" sizes="any"/><link rel="shortcut icon" href="/favicon.png?v=20260828" type="image/png"/><link rel="apple-touch-icon" href="/favicon.png?v=20260828"/></head><body>{children}<Script id="data-layer" strategy="beforeInteractive">{`window.dataLayer=window.dataLayer||[];`}</Script><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/></body></html>}
