import Link from 'next/link';

const cats=['Binicili','İtmeli','Akülü','Elektrikli','Endüstriyel Süpürücü','Tek Diskli','Orta Sınıf Binicili','Kombine Makine'];
const sectors=['Fabrikalar','AVM’ler','Depolar','Otoparklar','Hastaneler','Oteller','Marketler','Okullar','Belediyeler','Lojistik Merkezleri'];
const perks=[['♙','Uzman Yönlendirme','İhtiyacınıza göre makine sınıfı'],['◈','Geniş Çözüm Yelpazesi','Farklı saha tipleri için seçenekler'],['✹','Teknik Servis Desteği','Planlı bakım ve servis akışı'],['⚙','Yedek Parça Süreci','Uyumluluk teyitli yönlendirme'],['◉','Satış Sonrası Destek','Talebinize göre destek kanalı']];

export default function Home(){return <main className="refHome">
  <div className="refTop"><div><span>♢ Türkiye Geneli Hizmet</span><span>◉ Uzman Teknik Destek</span><span>◇ Yedek Parça Süreci</span></div><div><a href="https://wa.me/905550000000">◉ WhatsApp</a><Link href="/iletisim">İletişim talebi</Link></div></div>
  <header className="refHeader"><Link className="refLogo" href="/"><b>ZEMİN YIKAMA</b><span>MAKİNELERİ</span></Link><nav><Link className="active" href="/">ANA SAYFA</Link><Link href="/makineler">ZEMİN YIKAMA MAKİNELERİ⌄</Link><Link href="/servis">HİZMETLER⌄</Link><Link href="/sektorler">SEKTÖREL ÇÖZÜMLER⌄</Link><Link href="/blog">BLOG</Link><Link href="/iletisim">İLETİŞİM</Link></nav><Link className="refButton" href="/teklif-al">TEKLİF AL</Link></header>
  <section className="refHero"><div className="heroShade"/><div className="refHeroCopy"><strong>PROFESYONEL</strong><h1>ZEMİN YIKAMA<br/>MAKİNELERİ</h1><p>Fabrika, AVM, depo, otopark, hastane ve büyük ticari alanlar için profesyonel zemin temizleme çözümlerini keşfedin.</p><div><Link className="refButton" href="/makineler">MODELLERİ İNCELE</Link><Link className="outlineButton" href="/teklif-al">FİYAT TEKLİFİ AL</Link><Link className="greenButton" href="/iletisim?kanal=whatsapp">◉ WHATSAPP’TAN BİLGİ AL</Link></div></div><aside className="refHeroPerks"><p><b>↗</b> Etkili Temizlik Yaklaşımı</p><p><b>♧</b> Verimli Kullanım Planı</p><p><b>♙</b> Ergonomik ve Kullanıcı Odaklı</p><p><b>♢</b> Dayanıklı Çözüm Seçimi</p></aside><div className="dots">● ● ● ●</div></section>
  <section className="refCats">{cats.map((c,i)=><Link href={i===0||i===6?'/makineler/binicili':i===1||i===2||i===3||i===5?'/makineler/iticili':i===4||i===7?'/makineler/supuruculer':'/makineler'} key={c}><div><b>{c}</b><span>Zemin Temizleme<br/>Makineleri</span><small>İNCELE</small></div><div className={`catMachine cat${i}`}><i/><em/><b/></div></Link>)}</section>
  <section className="refPerks">{perks.map(p=><div key={p[1]}><i>{p[0]}</i><p><b>{p[1]}</b><span>{p[2]}</span></p></div>)}</section>
  <section className="refSectors"><div className="refSectionTitle"><div><small>SEKTÖREL ÇÖZÜMLER</small><h2>Her Sektöre Özel Zemin Temizleme Çözümleri</h2></div><Link className="refButton" href="/sektorler">TÜM SEKTÖRLER</Link></div><div className="sectorStrip">{sectors.map((s,i)=><Link href={`/sektorler/${['fabrika','avm','depo','otopark','hastane','otel','market','okul','belediye','lojistik'][i]}`} key={s}><div className={`sectorPic sp${i}`}/><b>{s}</b></Link>)}</div></section>
  <div className="refSticky"><a href="tel:+905550000000">☎ <span><b>HEMEN ARA</b><small>TELEFON TALEBİ</small></span></a><a href="https://wa.me/905550000000">◉ <span><b>WHATSAPP</b><small>HIZLI BİLGİ AL</small></span></a><Link href="/teklif-al">▣ <span><b>TEKLİF AL</b><small>ÜCRETSİZ TALEP</small></span></Link></div>
 </main>}
